### ISSUE TITLE
Highlight sorted headers that already have a default background header style?

### ISSUE THREAD

**Issue by ixodid198** [glin/reactable#101]
From [here](https://glin.github.io/reactable/articles/cookbook/cookbook.html) I see how to highlight sorted headers. Is it possible to identify the sorted header column as described if there is already a colour given to the headers.

In this example, with the comments included the highlighted of the sorted column works as expected. If the comments are removed and the column headers are given a default background colour then the sorted columns are not identified.

Is it possible for the column headers to be dark, then switch to the sorted column header style as indicated in the css when they are sorted, then back to dark style when another column is sorted?

```
library(shiny)
library(reactable)

ui <- fluidPage(
  theme = "test.css",
  reactableOutput("table")
)

server <- function(input, output, session) {
  output$table <- renderReactable({
    reactable(iris,
              defaultColDef = colDef(
                # headerStyle = list(background = header_background_col,
                #                    color = header_text_col,
                #                    fontWeight = "normal",
                #                    fontSize = "12px",
                #                    fontFamily = ss_font),
                
                # Use css to style the header of the sorted column
                headerClass = "sort-header",
                
                # Style of numbers in table
                style = list(fontFamily = ss_font,
                             fontSize = "12px"))
    )
  })
}

shinyApp(ui, server)
```

**Comment by glin** [comment]
It sounds like you want some default styles on column headers, and then another set of styles on those headers if they're being sorted. If so, I'd recommend doing all of the styling in external CSS. The `headerStyle` argument adds inline styles, which usually takes priority over CSS rules: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

Here's the doc example, but with default styling on all headers:

````
```{r}
reactable(
  iris[1:5, ],
  defaultColDef = colDef(headerClass = "table-header"),
  bordered = TRUE
)
```

```{css, echo=FALSE}
.table-header {
  background: rgba(0, 0, 0, 0.02);
}

.table-header[aria-sort="ascending"],
.table-header[aria-sort="descending"] {
  background: rgba(0, 0, 0, 0.08);
}
```
````

![reactable output](https://user-images.githubusercontent.com/20401866/101267161-7f0af000-371b-11eb-9f6c-7c2e04ee6471.png)

**Comment by ixodid198** [comment]
Super helpful as always. Many thanks.
