### ISSUE TITLE
Is there a way to add bar charts on the background of the cell?

### ISSUE THREAD

**Issue by Uriahf** [glin/reactable#103]
I'm really enjoying reactable and I'm trying to replace all my DT tables to reactables.

I'd like to add bar Charts the same way as it is shown here:
[](https://glin.github.io/reactable/articles/twitter-followers/twitter-followers.html
)

But I find it expensive in terms of space. Is it possible to put the bar charts behind the cell's value like in DT?
![barcharts](https://user-images.githubusercontent.com/11351434/101649756-ebe7f800-3a43-11eb-8b1c-0a0b07775564.PNG)

[](https://rstudio.github.io/DT/010-style.html)

**Comment by glin** [comment]
I'm not sure how `DT::styleColorBar` works, but assuming it just adds some background styling to the cell, then yes. You can find the exact styling that `styleColorBar` adds, find the % width of the bar (like in https://glin.github.io/reactable/articles/cookbook/cookbook.html#bar-charts), then add the same styling to the cell using the `colDef(style = )` argument.

Here's a quick attempt at this. I right-click+Inspect'd one of the DT table cells to find what styles it had in the browser developer tools:

```r
library(DT)
library(magrittr)

df <- mtcars[, 1:4]

datatable(df) %>%
  formatStyle(names(df),
              background = styleColorBar(range(df), "lightblue"),
              backgroundSize = "98% 88%",
              backgroundRepeat = "no-repeat",
              backgroundPosition = "center")
```

![Inspecting styles of DT::styleColorBar in dev tools](https://user-images.githubusercontent.com/20401866/102695841-863bfe80-41ef-11eb-84e7-6adbacd5e539.png)

Then I added the same background styling via the `style` argument:
```r
library(reactable)

bar_style <- function(width = 1, color = "lightblue") {
  # The linear-gradient stop position is 100% - width%
  position <- paste0(100 - width * 100, "%")
  list(
    background = sprintf("linear-gradient(90deg, transparent %1$s, %2$s %1$s)", position, color),
    backgroundSize = "98% 88%",
    backgroundRepeat = "no-repeat",
    backgroundPosition = "center"
  )
}

df <- mtcars[, 1:4]

reactable(
  df,
  columns = list(
    mpg = colDef(
      style = function(value) {
        bar_style(width = value / max(df$mpg), color = "lightblue")
      }
    ),
    disp = colDef(
      style = function(value) {
        bar_style(width = value / max(df$disp), color = "#ddd")
      }
    )
  )
)
```

![reactable output](https://user-images.githubusercontent.com/20401866/102695968-8092e880-41f0-11eb-89b6-e9db0b9284d1.png)

**Comment by Uriahf** [comment]
That's amazing! I've tried it out and it worked really well. 

Do you have an easy way to implement the same styling for negative / positive bars example?

**Comment by glin** [comment]
For a negative/positive bar, you could take a similar approach to the cookbook example (https://glin.github.io/reactable/articles/cookbook/cookbook.html#positive-and-negative-values) and split the background into 2 halves, where the negative bar takes the first 50%, and the positive bar takes the second 50%. CSS linear gradients let you draw bars anywhere along the background, so for example:

A positive 25% bar could be drawn like: 
```css
/* Transparent until 50%, then lightblue from 50-75%, then transparent from 75% onward */
linear-gradient(90deg, transparent 50%, lightblue 50%, lightblue 75%, transparent 75%)
```

And a negative 25% bar could be drawn like:
```css
/* Transparent until 25%, then lightblue from 25-50%, then transparent from 50% onward */
linear-gradient(90deg, transparent 25%, lightblue 25%, lightblue 50%, transparent 50%)
```


Here's a code example of this:

```r
library(reactable)

bar_style_pos_neg <- function(width = 1, pos_fill = "lightblue", neg_fill = "lightpink") {
  # Split the background into 2 halves for negative and positive bars.
  # For positive bars, draw the bar from 50% to 50% + width
  # For negative bars, draw the bar from 50% + -width to 50%
  position <- paste0((0.5 + width / 2) * 100, "%")
  if (width >= 0) {
    background <- sprintf("linear-gradient(90deg, transparent 50%%, %2$s 50%%, %2$s %1$s, transparent %1$s)", position, pos_fill)
  } else {
    background <- sprintf("linear-gradient(90deg, transparent %1$s, %2$s %1$s, %2$s 50%%, transparent 50%%)", position, neg_fill)
  }

  list(
    background = background,
    backgroundSize = "98% 88%",
    backgroundRepeat = "no-repeat",
    backgroundPosition = "center"
  )
}

df <- mtcars[, 1:4]

reactable(
  sleep,
  columns = list(
    extra = colDef(
      style = function(value) {
        bar_style_pos_neg(width = value / max(abs(sleep$extra)))
      }
    )
  ),
  bordered = TRUE
)
```

![reactable output](https://user-images.githubusercontent.com/20401866/104859367-7137b580-58ea-11eb-9b5e-a4761db39b01.png)

**Comment by Uriahf** [comment]
I can't thank you enough for this, thank you for your time and effort.
