### ISSUE TITLE
Sticky column group headers

### ISSUE THREAD

**Issue by mortandersen** [glin/reactable#107]
Hi.

Thank you for this wonderful package!

I'm having some trouble with fixing the column group header names when a certain height is chosen. See code below (you might have to view the actual table in a browser to see the problem)

    reactable(
      iris[1:50, ],
      pagination = FALSE,
      sortable = FALSE,
      height = 600,
      columns = list(
        Sepal.Length = colDef(name = "Length"),
        Sepal.Width = colDef(name = "Width"),
        Petal.Length = colDef(name = "Length"),
        Petal.Width = colDef(name = "Width")
      ),
      columnGroups = list(
        colGroup(name = "Sepal", columns = c("Sepal.Length", "Sepal.Width")),
        colGroup(name = "Petal", columns = c("Petal.Length", "Petal.Width"))
      )
    )

Is there a way to fix this issue? I want both the column group header name and the column name to stay fixed when scrolling down.

Thank you.

**Comment by glin** [comment]
Hi, unfortunately that's intended for now, sorry. I've looked into getting column group headers to stick before, but got stuck on limitations with the underlying table library (React Table). It might be possible to fix in the future though, so keep a look out.

**Comment by mortandersen** [comment]
Ok. Fair enough. Thank you for your answer and again thanks for the good work with this package! 
Do you (or anyone else reading this) know of any workarounds for this requested feature?

**Comment by glin** [comment]
This is now fixed in the development version (https://github.com/glin/reactable/commit/d9ac371fb1a5a06f5e878bedf1bfcabbeac2838d). Both the column group headers and filter cells should be sticky now:

```r
reactable(
  iris[1:50, ],
  pagination = FALSE,
  filterable = TRUE,
  bordered = TRUE,
  height = 300,
  columns = list(
    Sepal.Length = colDef(name = "Length"),
    Sepal.Width = colDef(name = "Width"),
    Petal.Length = colDef(name = "Length"),
    Petal.Width = colDef(name = "Width")
  ),
  columnGroups = list(
    colGroup(name = "Sepal", columns = c("Sepal.Length", "Sepal.Width")),
    colGroup(name = "Petal", columns = c("Petal.Length", "Petal.Width"))
  )
)
```

![reactable output](https://user-images.githubusercontent.com/20401866/104133310-65774c80-5348-11eb-8820-df9ef0d82a6a.png)
