### ISSUE TITLE
shiny: reactable not displayed with UI - fullpage()

### ISSUE THREAD

**Issue by petbrueck** [glin/reactable#108]
Hi again, 
not sure if best to ask here or at [RinteRface/fullPage](https://github.com/RinteRface/fullPage):
I am currently developing a Shiny App using the fullPage package for my UI, but I can't get the tables rendered. See code below. I saw that there is a [React wrapper ](https://github.com/alvarotrigo/react-fullpage) for the fullpage.js library but since I am not an advanced user, I am unsure if that could be of help. 

```
library(shiny)
library(reactable)
library(fullPage)

ui <- fullPage(
  fullSection(
    menu = "first",
    center = TRUE,
    reactableOutput("table")
  )
)
server <- function(input, output) {
  output$table <- renderReactable({
    reactable(iris)
  })
}
shinyApp(ui, server)
```
Any tips on how to get it running or if it is just not compatible would be highly appreciated. 

Thanks a lot for this great package which I am using a lot!

**Comment by glin** [comment]
Hi, I tried out that app, got a blank web page, and found some JavaScript errors in my browser JavaScript console:
```js
htmlwidgets.js:500 Uncaught TypeError: Cannot read property 'filter' of undefined
    at exports.OutputBinding.shinyBinding.find (htmlwidgets.js:500)
    at init_shiny.js:15
    at a (init_shiny.js:219)
    at initShiny (init_shiny.js:283)
```

It looks like an issue with all HTML widgets, particularly when rendering them as Shiny outputs. plotly and DT widgets get the same error. Try asking about this in the RinteRface/fullPage repo? I bet it's the same issue as this one: https://github.com/RinteRface/fullPage/issues/7
