### ISSUE TITLE
Export buttons

### ISSUE THREAD

**Issue by fmmattioni** [glin/reactable#11]
Fantastic package! Is it possible to have export buttons as {DT} does?

https://rstudio.github.io/DT/extensions.html#buttons

**Comment by dktanwar** [comment]
Yes, I agree. It would be great to have the export buttons as well.

**Comment by BenWoods** [comment]
I agree. This appears to be the only feature missing from DT that I regular use.

**Comment by glin** [comment]
Agreed it'd be useful as well. React Table doesn't support this out of the box, but it wouldn't too difficult to implement. Or at least provide a way to add custom buttons with access to the table instance/data, so users could do whatever they want (exporting, copying, etc.).

**Comment by fmmattioni** [comment]
Looking forward to it! I will update some of my shiny apps from {DT} to {reactable} once this is available.. I really love some of the functionalities here

**Comment by aiccu** [comment]
Amazing work on this package! And like @fmmattioni, I plan on migrating most of my dashboards over once this is aligned.

**Comment by DiegoConde** [comment]
Congratulations on this package. It´s amazing. I am migrating all my DT to reactable. When would it be possible to have the buttons to export the data? Thank you and congratulations for this work.

**Comment by fmmattioni** [comment]
@DiegoConde take a look at the package I created that you can easily implement download buttons in your rmarkdown :)
https://github.com/fmmattioni/downloadthis

**Comment by ssamberkar** [comment]
> @DiegoConde take a look at the package I created that you can easily implement download buttons in your rmarkdown :)
> https://github.com/fmmattioni/downloadthis

Thanks a lot, `reactable` and 'downloadthis' are awesome together, `crosstalk` just sweetens the recipe. Is it possible to save the filtered instance of a table by linking it to an Export button? Or is too difficult to implement?

**Comment by opendatasurgeon** [comment]
This feature would be nice too. I have recently moved away from `DT` package to this one because I no longer have to depend on StaackOverflow to get all my CSS working. Thanks for making this package.

**Comment by glin** [comment]
This is now possible to do in the development version (0.2.3.9000) using the new JavaScript API:
> * New JavaScript API to manipulate or access tables from JavaScript. Use this to create custom interactive controls, such as CSV download buttons, custom filter inputs, or toggle buttons for row grouping and row expansion ([#11](https://github.com/glin/reactable/issues/11), [#28](https://github.com/glin/reactable/issues/28), [#182](https://github.com/glin/reactable/issues/182), [#194](https://github.com/glin/reactable/issues/194)). Learn more in the [JavaScript API guide](https://glin.github.io/reactable/articles/javascript-api.html) or the [JavaScript API examples](https://glin.github.io/reactable/articles/examples.html#javascript-api).

There's no built-in export button, but instead, a `Reactable.downloadDataCSV()` JavaScript function that downloads the data to CSV and handles the messy details behind the scenes.

You can use this to implement your own CSV download button and style it however you want. The most basic download button could be one line of code:

```r
library(reactable)
library(htmltools)

htmltools::browsable(
  tagList(
    tags$button("Download as CSV", onclick = "Reactable.downloadDataCSV('cars-table', 'cars.csv')"),

    reactable(MASS::Cars93[, 1:5], elementId = "cars-table")
  )
)
```

Or if you wanted to reuse this download button in other tables, you could write a function for it:
```r
library(reactable)
library(htmltools)

csvDownloadButton <- function(tableId, label = "Download as CSV", filename = "data.csv") {
  htmltools::tags$button(
    label,
    onclick = sprintf("Reactable.downloadDataCSV('%s', '%s')", tableId, filename)
  )
}

htmltools::browsable(
  tagList(
    csvDownloadButton("cars-table", "Download as CSV", filename = "cars.csv"),

    reactable(MASS::Cars93[, 1:5], elementId = "cars-table")
  )
)
```

For a working demo, check out the [CSV download button example](https://glin.github.io/reactable/articles/examples.html#csv-download-button) in the docs. 

For more details on how to use the JavaScript API, check out the the [JavaScript API guide and reference](https://glin.github.io/reactable/articles/javascript-api.html).

And for more details on using the `Reactable.downloadDataCSV()` function, check out the [reference for `Reactable.downloadDataCSV()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-downloaddatacsv-). Right now, it's pretty limited in what it does, and just downloads the filtered dataset with sorting/grouping excluded and hidden columns included. However, future enhancements could include options to ignore filtering, exclude headers, exclude hidden columns, apply sorting, or even download to a different format. If you have any ideas to improve it, feel free to leave a comment or open a new issue.

**Comment by algo-se** [comment]
huuuuge! awesome work @glin

**Comment by dsolito** [comment]
Hello,
It's not working for me. Copying the CSV download button example and nothing happens.
Just this message in the console :
`ncaught ReferenceError: Reactable is not defined
    at HTMLButtonElement.onclick (index.html:15:67)
onclick @ index.html:15`

**Comment by xanderwallace85** [comment]
> Hello, It's not working for me. Copying the CSV download button example and nothing happens. Just this message in the console : `ncaught ReferenceError: Reactable is not defined at HTMLButtonElement.onclick (index.html:15:67) onclick @ index.html:15`

Hi @dsolito! I am facing the same issue. Have you found a solution for that?

**Comment by glin** [comment]
@dsolito @xanderwallace85 Do you have the latest development version (v0.2.3.9000) installed from GitHub? The version on CRAN (v0.2.3) doesn't have this feature yet.
