### ISSUE TITLE
getReactableState failes to work properly after table filtering

### ISSUE THREAD

**Issue by alon-sarid** [glin/reactable#110]
Hi. 

I use getReactableState() function for two purposes.
First, to allow the user to select rows for deletion. 
Second, to allow the user to select a specific raw for editing. 

The problem I discovered is that once deletion occurs the getReactableState() does not refresh, and keeps holding the indices of the deleted rows.  So I cannot get the actual number of selected rows.

example code:

          `
          library(shiny)
          library(reactable)
          
          data <- MASS::Cars93[1:5, 1:7]
          
          ui <- fluidPage(
            actionButton("delete", "Delete rows"),
            reactableOutput("table"),
            h3("selected rows:"),
            textOutput("selected_rows_output"),
            h6("notice that the deleted rows still apear")
          )
          
          server <- function(input, output, session) {
            rv <- reactiveValues(data = data)
            
            output$table <- renderReactable({
              reactable(rv$data, selection = "multiple", onClick = "select")
            })
            
            observeEvent(input$delete, {
              rows <- getReactableState("table", "selected", session)
              req(rows)
              rv$data <- rv$data[-rows, ]
              
              
            })
            
            selected_rows <- reactive({
              
              
              cat(getReactableState("table", "selected", session))
              
              
              getReactableState("table", "selected", session)
              
            })
            
            output$selected_rows_output <- renderText({
              
              text <- paste0("\n",selected_rows(),"\n")
              
            })
            
            
            
            
            
          }
          
          shinyApp(ui, server)
          `

**Comment by glin** [comment]
Hi, thanks for the report and reproducible example. Apparently, I unintentionally fixed this in some upcoming changes for the next release. I'll add a note to the news and let you know when it's available on GitHub. Thanks!

**Comment by glin** [comment]
This should now be fixed in the development version (https://github.com/glin/reactable/commit/d9ac371fb1a5a06f5e878bedf1bfcabbeac2838d). The NEWS item is:

> Selected rows now reset when the table data changes in Shiny (#110).
