### ISSUE TITLE
updateReactable does not update when you have custom cell in Shiny App

### ISSUE THREAD

**Issue by shambhu112** [glin/reactable#111]
Note the toy application below. Calling updateReactable in shiny App does not update the  "Detail" Column. Note other columns are getting updated but the custom column of "Detail" doe snot update.
```{r }


library(shiny)
library(reactable)
library(dplyr)


get_species_choice <- function(){
    sp <- as.character(unique(iris$Species))
    c("all.." , sp)
}

df <- as.data.frame(iris)

# This function returns a Custom Reactable instance of IRIS dataset. Note the Column "Detail"

iris_reactable <- function(d){
    reactable(d,
              filterable = TRUE ,
              striped = TRUE ,
              columns = list(
                  Species = colDef(
                      name = "Detail" ,
                      cell = function(value , index){
                          area <-df[index,]$Sepal.Width * df[index,]$Sepal.Length
                          tagList(
                                       div(style = list(fontWeight = 600 , fontSize = 12) , value) ,
                                       div(style = list(fontSize = 10) , paste("Area " ,area))
                          )

                      }
                  )
              ))
}

ui <- fluidPage(

    titlePanel("Reactable Bug Demo"),

    sidebarLayout(
        sidebarPanel(
            selectInput(inputId = "species" , label = "Species" , choices = get_species_choice())
        ),

        mainPanel(
            reactableOutput("the_table")
        )
    )
)



# update Reactable does not update the "Detail" column
server <- function(input, output) {
    selected_species <- reactive(input$species)

    output$the_table  <- renderReactable(iris_reactable(df))

    observe({
        x <- selected_species()
        print(x)

        rt <- df
        if(x != "all.."){
            rt <- dplyr::filter(df , Species == x)
        }

       print(nrow(rt))
        updateReactable(outputId = "the_table" , data = rt)
    })
}


shinyApp(ui = ui, server = server)

```

[](url)

**Comment by shambhu112** [comment]
here is live demo of the bug [https://webscale.shinyapps.io/reactablebug/](url)

**Comment by glin** [comment]
Hi, thanks for the bug report. This is the same issue as https://github.com/glin/reactable/issues/109, so we'll track it there and close this.

Unfortunately there's not likely to be a fix for this soon, but I suggested two possible workarounds.

https://github.com/glin/reactable/issues/109#issuecomment-761905648

> When using `updateReactable(data = )`, the table data updates but any custom render functions or style functions in R don't get rerun for the new data. Unfortunately, this was an oversight when adding this feature, and I don't actually know how to fix this. It might have to be a documented limitation for now.
>
> There are two workarounds I can think of:
>
> One would be to write all of custom render and style functions in JavaScript instead of R, so they get reapplied when the table data changes. The downside here is that you have to write JavaScript instead of R.
>
> Another workaround would be to make the table data a reactive value that can be updated, so the table gets re-rendered automatically when you update the data. The downside with this is that it's a fresh re-render, so any sorting/filtering state would be reset each time.
>
> And this isn't really a workaround, but if you just want a slider that filters the table, you can look into Crosstalk filtering.
