### ISSUE TITLE
Dates in yearmon fotmat from package zoo

### ISSUE THREAD

**Issue by lemuelemos** [glin/reactable#122]
It's possible to put dates in yearmon format, preserving the order from dates?

**Comment by glin** [comment]
Hi, there's no built-in yearmon formatter, but it is possible if you use a custom render function: https://glin.github.io/reactable/articles/examples.html#custom-data-formatting-1

For example:
```r
library(reactable)

data <- data.frame(
  date = as.Date(c("2019-01-02", "2019-03-15", "2019-09-22", "2020-01-05"))
)

reactable(
  data,
  columns = list(
    date = colDef(cell = function(value) {
      zoo::as.yearmon(value)
    })
  )
)
```
Custom render functions only affect display, so the order of the dates will be preserved.

**Comment by lemuelemos** [comment]
Perfect. Thanks @glin !
