### ISSUE TITLE
pagination resets defaultExpanded = TRUE

### ISSUE THREAD

**Issue by gofford** [glin/reactable#126]
Hey @glin -- quick suggestion

If I have both `pagination` and `defaultExpanded` set to `TRUE`, only page 1 of the table is expanded. If I flip to page 2 all rows are then collapsed. Is there a method or setting which makes sure that _all_ pages have expanded rows? 

I've not been able to resolve myself yet so thought I'd ask!

**Comment by glin** [comment]
Hey, this was recently fixed as part of https://github.com/glin/reactable/issues/35, so try installing the dev version. The exact NEWS item for the fix was:

> * In `reactable()`, `defaultExpanded = TRUE` now expands all rows in the table,  not just rows on the first page.
