### ISSUE TITLE
Only show markers in leaflet selected from reactable when using crosstalk

### ISSUE THREAD

**Issue by tedmoorman** [glin/reactable#127]
With crosstalk I'm using R's leaflet package to show a map that I filter with reactable. When I select a single row, I see too many markers on the map, even though the opacity of the unselected markers is reduced. I would like for all markers to disappear except the ones I've chosen from the table. You can sort of see what I'm talking about here: [https://glin.github.io/reactable/articles/examples.html#linked-selection-1]. Just imagine many, many more markers.

Maybe there's a quick fix from reactable. Or maybe the problem has to do with crosstalk or leaflet. I'm cross referencing in all issue forums. Please see [https://github.com/rstudio/crosstalk/issues/84] and [https://github.com/rstudio/leaflet/issues/726].

**Comment by glin** [comment]
Hi, I think this is most likely a leaflet thing. reactable only interacts with leaflet through Crosstalk, and doesn't do anything specific for leaflet. Other Crosstalk examples with leaflet seem to work the same too, like at https://rstudio.github.io/crosstalk/index.html. There may be some config option in leaflet to control the unselected marker opacity, so I'd guess the leaflet repo is the best place to ask about it.
