### ISSUE TITLE
How to restore the table before sort

### ISSUE THREAD

**Issue by rickyking** [glin/reactable#134]
Hi,

This is a great library. Thanks for putting this together!

Just one question: how can I reset the sort? When I click it rotate from asc to desc but no way to go back to default order?

**Comment by glin** [comment]
Hi, you can reset the sort by holding the shift key while sorting. If the shift key is held down, the sort order will go: Ascending, Descending, Default. I've realized this isn't specifically documented anywhere, so I'll get this added to the docs.

**Comment by rickyking** [comment]
Thanks!

**Comment by rickyking** [comment]
Oh just thank you for your great library. This is what I built with your library: 

https://www.trading-logic.com/MarketDashboard.html

**Comment by D3SL** [comment]
I found this post looking for this exact answer, but have one additional question: Is there a way to restore `defaultSorted` after un-sorting through shift clicking?
