### ISSUE TITLE
Recovering information from the parent line after a group by

### ISSUE THREAD

**Issue by cmandier** [glin/reactable#136]
Hi, 

First of all thank you for your library, it provides great ways for visualizing tables.
 
When using it, I encountered a limitation. Indeed, I made a Group By, to allow myself to elaborate a parent line summarizing the information of the child lines, and to sum up the values to reach a grand total for each code on the parent line. (Example attached)

I later added in checkboxes, to allow the user to select the parent rows they needed to copy into a new table. However, I noticed that the information contained in the parent row could not be selected and stored to allow for a copy to be made in a new table. Only the child rows were stored, which resulted in losing the work on grouping and summing up the numbers.

Would you know of a solution to this problem?

Thank you

![table](https://user-images.githubusercontent.com/73120865/111610349-8d1ce200-87db-11eb-904d-d2774cf59d63.PNG)

**Comment by glin** [comment]
Hi, would you mind posting a minimal code example of what you're trying to do? I think I get the gist of the problem, but am not 100% sure.

From what I understand, you'd like to get the data from an aggregate row in a Shiny app? If so, that's unfortunately not possible today. The aggregated rows are calculated on the client side (in the browser) and not accessible to R or the Shiny app. But that would be possible to do some day, so I could take this as a feature request. For now, one alternative I can think of would be to aggregate the data in R. When a user selects a group of rows, you could subset the data and summarize the rows manually.

**Comment by cmandier** [comment]
Hi!
Thank you for your answer. 
Indeed, I want to get the data of an aggregate row in a Shiny application. I took your idea into account and I made sure to manually subset the data separately. It works perfectly well!
