### ISSUE TITLE
colFormat(digits) doesn't work with bar_chart

### ISSUE THREAD

**Issue by JodyStats** [glin/reactable#14]
`colFormat(digits)` works normally but not when rendering it together with bar_chart. Inconsistent digit formatting causes the barchart to appear inconsistent in length and alignment.

```r
library(reactable)
library(htmltools)

# It works
reactable::reactable(iris, columns = list(
  Sepal.Length = colDef(format = colFormat(digits = 5))
))

# It does not work 
reactable::reactable(iris, columns = list(
  Sepal.Length = colDef(
    format = colFormat(digits = 5),
    cell = function(value) {
      width <- paste0(value / max(iris$Sepal.Length) * 100, "%")
      bar_chart(value, width = width)
    })
))
```

![Image](https://user-images.githubusercontent.com/57651432/69718454-82f84f80-1162-11ea-8e4e-8dc0ad18849b.jpg)

**Comment by glin** [comment]
Custom cell renderers currently override any formatting done by the built-in formatters. Looks like that isn't documented or warned about, so that was an oversight, sorry. In the future, it might be possible to use the formatted cell value in a cell renderer. But for now, you'll have to format data manually in the cell renderer. 

For example, using `format()` to add digits to the bar chart label:

```r
library(reactable)
library(htmltools)

# Render a bar chart with a label on the left
bar_chart <- function(label, width = "100%", height = "16px", fill = "#00bfc4", background = NULL) {
  bar <- div(style = list(background = fill, width = width, height = height))
  chart <- div(style = list(flexGrow = 1, marginLeft = "8px", background = background), bar)
  div(style = list(display = "flex", alignItems = "center"), label, chart)
}

reactable::reactable(iris, columns = list(
  Sepal.Length = colDef(
    cell = function(value) {
      width <- paste0(value / max(iris$Sepal.Length) * 100, "%")
      label <- format(value, nsmall = 5)
      bar_chart(label, width = width)
    })
))
```

![image](https://user-images.githubusercontent.com/20401866/69879739-d87d4b00-128d-11ea-89c8-6f8aa6f10255.png)

**Comment by JodyStats** [comment]
Thank you @glin. That solves the issue perfectly. I enjoy using your package, and converting all my DataTables to reactable.

**Comment by priyankagagneja** [comment]
Its not working for me somehow with format() also, I am working with $ values that need thousands seprator also. I tried using paste0() also, but none works.

**Comment by lesliejmatthews** [comment]
This does not work for me.  The nsmall adds trailing zeros, but bar widths are still inconsistent if number to left of the decimal point varies in number of digits.  Still does not right-justify the numbers to the left of the bars as desired.
