### ISSUE TITLE
Puting borders beneath specific rows

### ISSUE THREAD

**Issue by LucasTremlett** [glin/reactable#140]
I'm trying to put horizontal black borders beneath specific rows of a table. I haven't found any examples on how to do this online. 

For example, how can I get the table generated by `reactable(head(cars))` to have a black border beneath the second and fourth row, like in the image below?

![image](https://user-images.githubusercontent.com/65822123/113571930-897cbe00-9617-11eb-8c55-66e9698b0dab.png)

**Comment by glin** [comment]
Hi, for simple cases where the data is presorted and sorting is disabled, you could conditionally add a cell border style for particular row indices like:
```r
reactable(
  head(cars),
  defaultColDef = colDef(style = function(value, index) {
    if (index %in% c(2, 4)) {
      list(borderBottom = "2px solid black")
    }
  })
)
```
![reactable output](https://user-images.githubusercontent.com/20401866/114318868-8b8dc380-9ad4-11eb-9e76-ed1e2f5488b9.png)

Assuming you want borders between groups though, it gets trickier if the table can be sorted. The borders may no longer make sense after sorting:
![sorted reactable](https://user-images.githubusercontent.com/20401866/114318890-9f392a00-9ad4-11eb-90aa-86a9b8f04a25.png)

If your table can be sorted, I'd instead recommend a JavaScript based approach like in this cookbook example: https://glin.github.io/reactable/articles/cookbook/cookbook.html#borders-between-groups-of-data

**Comment by LucasTremlett** [comment]
Thank you!
