### ISSUE TITLE
How to filter missing/empty values

### ISSUE THREAD

**Issue by adayim** [glin/reactable#145]
I want to use this package for data quality check. So some times I want to filter rows with missing values. But it seems like the filtering does not allow for missing/empty value filtering. Is there any way to do that? I have pasted my code below and it's really simple one.  And is it possible to write filtering expression in the filtering box or only the value is supported?

```r
library(reactable)

rows <- 1000
dates <- seq.Date(as.Date("2018-01-01"), as.Date("2018-12-01"), "day")
data <- data.frame(
  index = seq_len(rows),
  date = sample(dates, rows, replace = TRUE),
  city = sample(names(precip), rows, replace = TRUE),
  state = sample(rownames(USArrests), rows, replace = TRUE),
  temp = round(runif(rows, 0, 100), 1),
  stringsAsFactors = FALSE
)

data[, c(2:5)] <- lapply(data[, c(2:5)], function(x){
  x[sample(1:length(x), floor(runif(1, 0, 100)))] <- NA
  x
})

reactable(
  data,
  filterable = TRUE,
  minRows = 10,
  highlight = TRUE,
)
```

**Comment by glin** [comment]
Hi, this isn't possible with the built-in filters today, but it may be possible when custom filtering gets added (related: https://github.com/glin/reactable/issues/90). Right now, the filters only support string matching on the value.

For alternatives, you could write a custom filter in Shiny if it's possible to use Shiny. Or you could use Crosstalk with an external filter for missing values. I don't think it's possible to filter missing values with the built-in Crosstalk filters, but you could write a custom filter to do that ([reference](https://rstudio.github.io/crosstalk/authoring.html#filtering)). Here's a quick example of a custom checkbox that filters missing `temp` values, which you can adapt:

```r
library(reactable)
library(crosstalk)
library(htmltools)

rows <- 1000
dates <- seq.Date(as.Date("2018-01-01"), as.Date("2018-12-01"), "day")
data <- data.frame(
  index = seq_len(rows),
  date = sample(dates, rows, replace = TRUE),
  city = sample(names(precip), rows, replace = TRUE),
  state = sample(rownames(USArrests), rows, replace = TRUE),
  temp = round(runif(rows, 0, 100), 1),
  stringsAsFactors = FALSE
)

data[, c(2:5)] <- lapply(data[, c(2:5)], function(x){
  x[sample(1:length(x), floor(runif(1, 0, 100)))] <- NA
  x
})

shared_data <- SharedData$new(data)

tbl <- reactable(
  shared_data,
  filterable = TRUE,
  minRows = 10,
  highlight = TRUE,
)

checkbox_filter <- function(id, label, shared_data, group, value) {
  values <- shared_data$data()[[group]]
  keys <- shared_data$key()[which(values %in% value)]
  
  script <- sprintf("
    window['__ct__%s'] = (function() {
      const handle = new window.crosstalk.FilterHandle('%s')
      const keys = %s
      return {
        filter: function(value) {
          if (!value) {
            handle.clear()
          } else {
            handle.set(keys)
          }
        }
      }
    })()
  ", id, shared_data$groupName(), jsonlite::toJSON(keys))
  
  div(
    tags$input(
      id = id,
      type = "checkbox",
      onclick = sprintf("window['__ct__%s'].filter(this.checked)", id)
    ),
    tags$label(`for` = id, label),
    tags$script(HTML(script))
  )
}

browsable(
  div(
    checkbox_filter("filter_temp", "Filter missing temperatures", shared_data, "temp", NA),
    tbl
  )
)
```

![reactable output with checkbox filter](https://user-images.githubusercontent.com/20401866/116795775-fc554980-aa9c-11eb-804b-6ea248571a5e.png)

**Comment by adayim** [comment]
Thanks, this is helpful. But providing a method for filtering any variables with missing or empty values would be more appreciated. I used DT package instead to deal with this and I found [a solution](https://github.com/rstudio/DT/issues/322#issuecomment-234793593) for that. The basic idea is to replace the missing or empty values and return a custom one instead, may be render as "missing" value. Maybe consider all the missing, empty values as "missing"? And for space only values? This becomes complicated. Don't know a better way for that.

**Comment by glin** [comment]
Custom filtering is now possible in the latest development version (v0.2.3.9000):

> * Column filtering and table searching can now be customized. Learn more in the [Custom Filtering guide](https://glin.github.io/reactable/articles/custom-filtering.html).
>   * `reactable()` gains a `searchMethod` argument to use a custom JavaScript function for global table searching ([#222](https://github.com/glin/reactable/issues/222)).
>   * `colDef()` gains a `filterMethod` argument to use a custom JavaScript function for column filtering ([#9](https://github.com/glin/reactable/issues/9), [#90](https://github.com/glin/reactable/issues/90), [#145](https://github.com/glin/reactable/issues/145)).
>   * `colDef()` gains a `filterInput` argument to render a custom filter input for column filtering ([#9](https://github.com/glin/reactable/issues/9)).

My example from earlier is now easier to do with reactable only, no Crosstalk or Shiny needed. Here's a modified version of the checkbox filter using a custom filter method that I've added to the docs: https://glin.github.io/reactable/articles/custom-filtering.html#external-checkbox-filter

You could also filter for missing values in other ways, like writing a custom filter method that understands a custom keyword/expression to show missing values only, and return rows with NA/null values.

**Comment by adayim** [comment]
Fantastic, thank you. I will give it a try.
