### ISSUE TITLE
NA's in count when grouping in reactable

### ISSUE THREAD

**Issue by aavanesy** [glin/reactable#148]
Hello,

Please see a sample code

```
library(reactable)
data = data.frame(x = c('a','a','b','b'),
                  values = c(NA,5,3,NA))
reactable(data,
          groupBy = 'x')
```

![image](https://user-images.githubusercontent.com/48486871/116800899-2008a600-ab16-11eb-8894-1931015a2c19.png)

Is it possible to count only the lines which aren't NA?

I want to see a(1), b(1) instead

Thank you

**Comment by glin** [comment]
Hi, this hasn't been possible before, but it is now in the development version of reactable:

> * `colDef()` gains a `grouped` argument to customize rendering for grouped cells in `groupBy` columns ([#33](https://github.com/glin/reactable/issues/33), [#94](https://github.com/glin/reactable/issues/94), [#148](https://github.com/glin/reactable/issues/148)).

If you install the development version of reactable, you can use a custom grouped cell renderer that filters NAs out of the row count. I wrote up a few examples of that here: https://github.com/glin/reactable/issues/33#issuecomment-841733582
