### ISSUE TITLE
Selection option to update checkboxes using updateReactable doesnt work inside Modal

### ISSUE THREAD

**Issue by GEPEJR** [glin/reactable#149]
First of all, congratulations on the package! It is amazing and thanks for the help.

Selection option to update checkboxes using updateReactable doesnt work inside Modal.
However, when I leave the modal and enter again it works.

Below is the reproducible code:

library(shiny)
library(reactable)

ui <- fluidPage(
  actionButton("bt", "Load Modal")

)

server <- function(input, output, session) {
  
  output$table <- renderReactable({
    reactable(iris, selection = "multiple")
  })
  
  observeEvent(input$bt,{
    
    showModal(
      modalDialog(tags$head(tags$style(".modal-dialog{ width:1500px}")),
                  fluidRow(
                    titlePanel("reactable example"),
                    reactableOutput("table")
                  ),
      title = h2("Editar informações"),
      size = 'l',
      footer = tagList(
        modalButton("Cancel")
      )
    ))
    
    # Select rows
    updateReactable("table", selected = c(1, 3, 5))

  })
}
shinyApp(ui, server)

**Comment by GEPEJR** [comment]
I tried to switch to bsmodal library and presented the same error:

Code:

```
library(shiny)
library(reactable)



ui <- fluidPage(
  actionButton("bt", "Load Modal"),
  
  bsModal("modalExample", "Data Table", "bt", size = "large",
          reactableOutput("table")
  )

  
)

server <- function(input, output, session) {
  
    output$table <- renderReactable({

      reactable(iris, selection = "multiple")

    })

    observeEvent(input$bt, {
      updateReactable("table", selected = c(1, 3, 5))
    })

}
shinyApp(ui, server)

**Comment by glin** [comment]
Hi, in these example apps, `updateReactable()` is being run before the table even renders in the modal. This is more of a Shiny thing, and there's no way for reactable to handle this case.

I can't think of a great solution off the top of my head, but could you render the table with `defaultSelected` rows instead? Like:

```r
library(shiny)
library(reactable)

ui <- fluidPage(
  actionButton("bt", "Load Modal")
  
)

server <- function(input, output, session) {
  
  output$table <- renderReactable({
    reactable(iris, selection = "multiple", defaultSelected = c(1, 3, 5))
  })
  
  observeEvent(input$bt,{
    
    showModal(
      modalDialog(tags$head(tags$style(".modal-dialog{ width:1500px}")),
                  fluidRow(
                    titlePanel("reactable example"),
                    reactableOutput("table")
                  ),
                  title = h2("Editar informações"),
                  size = 'l',
                  footer = tagList(
                    modalButton("Cancel")
                  )
      ))
  })
}

shinyApp(ui, server)
```

Otherwise, you'll have to figure out some way to defer `updateReactable()` until after the modal is done rendering.

**Comment by GEPEJR** [comment]
> Hi, in these example apps, `updateReactable()` is being run before the table even renders in the modal. This is more of a Shiny thing, and there's no way for reactable to handle this case.
> 
> I can't think of a great solution off the top of my head, but could you render the table with `defaultSelected` rows instead? Like:
> 
> ```r
> library(shiny)
> library(reactable)
> 
> ui <- fluidPage(
>   actionButton("bt", "Load Modal")
>   
> )
> 
> server <- function(input, output, session) {
>   
>   output$table <- renderReactable({
>     reactable(iris, selection = "multiple", defaultSelected = c(1, 3, 5))
>   })
>   
>   observeEvent(input$bt,{
>     
>     showModal(
>       modalDialog(tags$head(tags$style(".modal-dialog{ width:1500px}")),
>                   fluidRow(
>                     titlePanel("reactable example"),
>                     reactableOutput("table")
>                   ),
>                   title = h2("Editar informações"),
>                   size = 'l',
>                   footer = tagList(
>                     modalButton("Cancel")
>                   )
>       ))
>   })
> }
> 
> shinyApp(ui, server)
> ```
> 
> Otherwise, you'll have to figure out some way to defer `updateReactable()` until after the modal is done rendering.

Perfect, I understood, this solutions solved my problem. tks a lot!
