### ISSUE TITLE
Easy way to add commas to all numeric colums?

### ISSUE THREAD

**Issue by smach** [glin/reactable#152]
Sorry I can't figure this out myself, but is there an easy way to add commas to all numeric columns without having to specify each column one by one, since the columns in my data set will vary? So if I've got data such as

```
mydata <- data.frame(
  Category = c("A", "B", "C"),
  January = c(1000, 4999, 42345),
  February = c(2000, 6342, 56734),
  March = c(3000, 6734, 75342)
)
```

I want columns January, February, and March to have commas; and then as I add more columns, I don't want to have to keep manually adding the next month to my table script.

**Comment by glin** [comment]
Yes, there are a few methods you could use to cut down on `colDef` repetition. One way is to specify default column options using `defaultColDef`. You could give all columns a `separators` formatter by default, like:
```r
library(reactable)

mydata <- data.frame(
  Category = c("A", "B", "C"),
  January = c(1000, 4999, 42345),
  February = c(2000, 6342, 56734),
  March = c(3000, 6734, 75342)
)

reactable(
  mydata,
  defaultColDef = colDef(
    format = colFormat(separators = TRUE)
  )
)
```
The thousands separator formatting only applies to numbers, so it'll just ignore the character column. Or if the formatter causes issues for a particular column, you could override the formatter for that column:
```r
reactable(
  mydata,
  defaultColDef = colDef(
    format = colFormat(separators = TRUE)
  ),
  columns = list(
    Category = colDef(format = colFormat())
  )
)
```

If you want finer control over formatting or which columns get formatted, you could also use a default custom cell render function:
```r
reactable(
  mydata,
  defaultColDef = colDef(
    cell = function(value) {
      # Format only numeric columns with thousands separators
      if (!is.numeric(value)) {
        return(value)
      }
      format(value, big.mark = ",")
    }
  )
)
```

---

Alternatively, you could programmatically generate column definitions for the data. It's more verbose, but sometimes useful when you want to reuse code for complex column definitions. For example, a function that takes a data frame and outputs a named list of column definitions:
```r
make_column_defs <- function(data) {
  lapply(data, function(x) {
    if (is.numeric(x)) {
      # Numeric columns
      colDef(format = colFormat(separators = TRUE))
    } else {
      # Default columns
      colDef()
    }
  })
}

reactable(
  mydata,
  columns = make_column_defs(mydata)
)
```

**Comment by smach** [comment]
This is great, thanks!!!
