### ISSUE TITLE
Allow column name to be used in details function for column

### ISSUE THREAD

**Issue by ksnap28** [glin/reactable#155]
Thank you for this package. I just started using it recently and it has been fantastic!

I have a table where the number of columns displayed and the names of those columns can vary. I would like to display details for some of the cells, however for my use case I need the name of the column to determine the information to show. Unfortunately, right now the details function only allows the row index to be used. Would it be possible to also allow the column name to be used?

I got this working in my local copy by including key as a parameter to the details callFunc function. I can do a pull request if this is something you would like to incorporate.

Here is an example image showing what I am trying to do:
![sample_table](https://user-images.githubusercontent.com/2623216/117219980-32efd480-adbb-11eb-94b3-ae7080aef393.png)

**Comment by glin** [comment]
Hi, I like the idea! If you want to submit a pull request, I'd be happy to review it.

**Comment by ksnap28** [comment]
Great! I submitted pull request #159
