### ISSUE TITLE
How to return data from a clicked row for more than 1 event?

### ISSUE THREAD

**Issue by Camil88** [glin/reactable#166]
I have a `reactable` table and try to display info from selected row. Actually, I can do this easily using `onClick="select"` and store data as reactive using `getReactableState` but the issue in my case is slightly different. I added 'Save' button to each row and use some JS to return data from given row. Now I want to return data separately - using 'Save' button and clicking in a row. Unfortunately, when I click in some row then no data is returned (not displayed by `output$text`). How can I can display row's data by clicking in a row if I use JS as in the example below?

Here is reproducible example. If you click 'Save' then window shows up and data is displayed. If you click in a row no data is displayed in the panel below the table:
```r
if (interactive()) {
    
    library(shiny)
    library(reactable)
    
    data <- cbind(MASS::Cars93[, 1:3], saveCol = NA)
    
    ui <- fluidPage(
        reactableOutput("table"),
        tags$h3('Row details to display if you click in a row:'),
        verbatimTextOutput("text")
    )
    
    server <- function(input, output) {
        
        selectedRow <- reactive(reactable::getReactableState("table", "selected"))
        
        output$table <- renderReactable({
            reactable(
                data,
                filterable = TRUE,
                searchable = TRUE,
                columns = list(
                    saveCol = colDef(
                        name = "",
                        sortable = FALSE,
                        cell = function() htmltools::tags$button("save")
                    )),
                #onClick = "select"
                onClick = htmlwidgets::JS(
                "function(rowInfo, colInfo) {
                    if (colInfo.id !== 'saveCol') {
                        return 'select'
                    }

                window.alert('Details for row ' + rowInfo.index + ':\\n' + JSON.stringify(rowInfo.row, null, 2))

                if (window.Shiny) {
                    Shiny.setInputValue('save', { index: rowInfo.index + 1 }, { priority: 'event' })
                    }
                }"
                )
            )
        })
        
        # display selected table's row
        output$text <- renderPrint({
            data[selectedRow(),]
        })
    }    
    shinyApp(ui, server)
}
```
If you uncomment `onClick="select"` and comment JS for `onClick` then clicking in a row works well but as I said, in my case I need someting else. In code above I added return 'select' in first if to return select for `onClick` but it doesn't work. Do you have any ideas how to get around it?

**Comment by glin** [comment]
In the example, the `onClick` function uses [`Shiny.setInputValue()`](https://shiny.rstudio.com/articles/communicating-with-js.html) to send the row index of the clicked button to Shiny, storing it in the input ID `"save"`:

```js
if (window.Shiny) {
  // Send the row index to Shiny as a named list with the clicked row index
  Shiny.setInputValue('save', { index: rowInfo.index + 1 }, { priority: 'event' })
}
```

You can then access the last clicked row index like `input$save$index`. For example, you could have `renderPrint()` display the clicked row data like this:

```r
output$text <- renderPrint({
  req(input$save)
  data[input$save$index, ]
})
```

**Comment by Camil88** [comment]
Ok, thanks for your answer. However, I've noticed that it doesn't work when I use modules. `input$save$index` always return NULL when clicked. Do I need to pass namespacing somehow?
