### ISSUE TITLE
defaultColDef with show = FALSE leads to no visible columns

### ISSUE THREAD

**Issue by aronatkins** [glin/reactable#171]
```r
reactable::reactable(
    data.frame(a=c(2,2,2), b=c(3,3,3)), 
    columns = list(
        a=reactable::colDef(show = TRUE)
    ), 
    defaultColDef = reactable::colDef(show = FALSE)
)
```

This results in no visible columns. I expected the `a` column to be shown.

Workaround is to not rely on `defaultColDef` and enumerate in `columns` every hidden column and use `show = FALSE`.

```r
reactable::reactable(
    data.frame(a=c(2,2,2), b=c(3,3,3)), 
    columns = list(
        a=reactable::colDef(show = TRUE),
        b=reactable::colDef(show = FALSE)
    )
)
```

```
> packageVersion("reactable")
[1] ‘0.2.3’
```

**Comment by glin** [comment]
Sorry about that - it's a bug that should be fixed in the next release:
> Setting `show = FALSE` as a default value in `defaultColDef()` now works (@csgillespie, #105).

Another workaround would be to install the development version if that's an option.

**Comment by aronatkins** [comment]
Thanks, @glin; sorry for not testing the GitHub version ahead of filing this duplicate.
