### ISSUE TITLE
How to right- and left-align background bar charts with custom fill?

### ISSUE THREAD

**Issue by benho89** [glin/reactable#179]
Hello.

Firstly, I hope I'm posting this question in the right place.

I'm having difficulty right- and left-aligning background bar charts in two separate columns in my `reactable` table. I've tried looking for a solution, including in the Demo Cookbook, but I either don't quite understand the examples online or I can't find anything that appears to do what I'd like. I have an example dataset and code below. I've tried leaning on a method outlined in the Demo Cookbook, but the bar charts in both columns remain left-aligned. Essentially, I'd like the bar chart and values/labels in column `a` to be right-aligned and vice-versa for column `b`. This will then give the appearance similar to a positive and negative bar chart. Is there a simpler way of going about this? I fear the code I have so far is making things a little more complicated than it may need to be.

```
library(tidyverse)
library(htmltools)
library(reactable)

data <- tibble(
  a = c(9.175783855, 11.81526856, 0.958313222, 5.616405204, 2.52481891,
        1.781139798, 1.440104888, 2.40162111, 5.144542917,8.254753493,
        6.651080016, 4.44758866, 2.714855098, 2.35523782, 2.20347958,
        6.761000611),
  b = c(3.87414355, 10.75733095, 6.823421855, 10.11946139, 3.677263099,
        4.287000085, 4.993322574, 2.691458126, 7.013314446, 4.900493424,
        8.649965459, 1.482655707, 0.20604618, 0.32892486, 2.161339902,
        4.55948858)
)

# Trying to render a bar chart in the background of the cell using an
# example from the Demo Cookbook.

bar_style <- function(width = 1, fill = "#e6e6e6", height = "75%", align = c("left", "right"), color = NULL) {
  align <- match.arg(align)
  if (align == "left") {
    position <- paste0(width * 100, "%")
    image <- sprintf("linear-gradient(90deg, %1$s %2$s, transparent %2$s)", fill, position)
  } else {
    position <- paste0(100 - width * 100, "%")
    image <- sprintf("linear-gradient(90deg, transparent %1$s, %2$s %1$s)", position, fill)
  }
  list(
    backgroundImage = image,
    backgroundSize = paste("100%", height),
    backgroundRepeat = "no-repeat",
    backgroundPosition = "center",
    color = color
  )
}

reactable(
  data,
  columns = list(
    a = colDef(style = function(value) {
      bar_style(width = value / max(data$a),
                fill = "#2c5e77", color = "#fff")
    },
    align = "right",
    format = colFormat(digits = 2)
    ),
    b = colDef(style = function(value) {
      bar_style(width = value / max(data$b),
                fill = "#2c5e77", color = "#fff")
    },
    align = "left",
    format = colFormat(digits = 2))
  ))
```

I'd also like to know whether there is a method of filling the bar charts in column `a` based on the color values in `a_fill`? The same goes for column `b` and `b_fill`.

```
a_fill <- c("#97233f", "#241773", "#0b162a", "#fb4f14", "#002244",
            "#002244", "#203731", "#000000", "#002244", "#008e97",
            "#4f2683", "#203731", "#004953", "#000000", "#002244",
            "#aa0000")

b_fill <- c("#002244", "#a5acaf", "#002244", "#e31837", "#d50a0a",
            "#0b2265", "#9f8958", "#03202f", "#773141", "#002244",
            "#000000", "#0085ca", "#a71930", "#00338d", "#002c5f",
            "#005a8b")
```

Any assistance will be greatly appreciated. Thank you.

**Comment by glin** [comment]
Hi, to right-align background bar charts, trying adding `align = "right"` on the `bar_style()` function for column `a`:
```r
    a = colDef(style = function(value) {
      bar_style(width = value / max(data$a),
                fill = "#2c5e77", color = "#fff", align = "right")
    },
```
You can also find an example of a right-aligned bar in the `hp` column here: https://glin.github.io/reactable/articles/cookbook/cookbook.html#background-bar-charts

To customize the bar chart fill based on an external vector of colors, you could use the second argument of the style function, `index`, which is the row index for that cell: https://glin.github.io/reactable/articles/conditional-styling.html#r-functions. With the row index, you could then get the color for a cell in column `a` like `a_fill[index]`.

I don't think I have any examples of conditional styling using the `index` argument, but here's a very similar example for custom rendering: https://glin.github.io/reactable/articles/cookbook/cookbook.html#show-data-from-other-columns-r

**Comment by benho89** [comment]
Thank you, @glin. This is a great help!
