### ISSUE TITLE
Data is not displayed if column name has `[` or `]`

### ISSUE THREAD

**Issue by statquant** [glin/reactable#187]
Hello, the following breaks for me when trying to render a `data.table` but not a `data.frame`:
```
reactable(data.frame(x=1:3, y=1:3))     
```
![image](https://user-images.githubusercontent.com/3612473/130249353-b26d0247-8ee1-47a4-86c9-2eeca2990c18.png)
```
reactable(data.frame(x=1:3, `y_[]`=1:3))
```
![image](https://user-images.githubusercontent.com/3612473/130249814-247202ae-725c-4b9d-b8d3-1f1e51b1821f.png)
```
reactable(data.table(x=1:3, `y_[]`=1:3))
```
![image](https://user-images.githubusercontent.com/3612473/130249330-b5b92673-c419-42bb-a224-e8c0f1106d10.png)

Many thanks for the package

**Comment by glin** [comment]
That's a good catch, thanks for the report. This is now fixed in the development version (https://github.com/glin/reactable/commit/f9b6c81de1fcede08e44b99e7cb6f828c06b1566):

> * Columns with square brackets (`[` or `]`) in their column name now render correctly ([#187](https://github.com/glin/reactable/issues/187)).

**Comment by jonocarroll** [comment]
Just for reference, the same is/was true for a `tibble` and likely any structure which preserves `[` in column names.

`data.frame` typically converts names with `make.names()` so this didn't come up so easily with those, but is there any interest in preserving column names through `reactable()`?
