### ISSUE TITLE
Header rendering by default removes additional spaces between words

### ISSUE THREAD

**Issue by szmsu2011** [glin/reactable#191]
Thanks for the continuous development of the package.

It seems that the header rendering by default removes additional spaces between words. I am unsure how to turn it off.

Example (not an actual use case, demo only):

```r
library(tidyverse)
library(htmlwidgets)
library(reactable)

packageVersion("reactable")
#> [1] '0.2.3.9000'

## Attempt 1
iris %>%
  reactable(columns = list(Sepal.Length = colDef(name = "Sepal    Length")))

## Attempt 2
iris %>%
  reactable(columns = list(Sepal.Length = colDef(header = JS("
    function() {
      return 'Sepal    Length';
    }
  "))))
```

Wanted and expected:

![expected](https://user-images.githubusercontent.com/77832417/130465112-0f84067e-a7e1-4d1e-b6f0-6fe67db7a6f1.png)

Actual result:

![actual](https://user-images.githubusercontent.com/77832417/130465526-12676910-3d25-430c-a75e-3149eabf555d.JPG)

I was unable to add additional spaces in the header name for `Sepal.Length`.

Could you please advise if it is achievable?

Thank you in advance.

**Comment by glin** [comment]
Hi, [browsers collapse whitespace in HTML by default](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace), so multiple spaces end up appearing as a single space. If you want to preserve whitespace, you can set the [`white-space: pre`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) CSS property on your content:
```r
# Preserve whitespace in the header
iris %>%
  reactable(
    columns = list(Sepal.Length = colDef(name = "Sepal    Length", headerStyle = list(whiteSpace = "pre")))
  )

# Or preserve whitespace in the entire table
iris %>%
  reactable(
    columns = list(Sepal.Length = colDef(name = "Sepal    Length")),
    style = list(whiteSpace = "pre")
  )
```

There are a few other ways to put multiple spaces in HTML without CSS (see https://blog.hubspot.com/website/html-space), but I like the CSS method for the flexibility.
