### ISSUE TITLE
Downloading Reactable table in excel format?

### ISSUE THREAD

**Issue by kaya-atakan** [glin/reactable#194]
Hi,

I'm using reactable tables to display data in our daily, weekly and monthly reports. More often than not, the other departments that we send our reports to want  to download the table as an excel format to do further analysis.  So, could that feature be added  as an extra field as in the case of, for example, searchable = TRUE field? So, in this case, it would be suffice to add download = TRUE as an extra field .

**Comment by algo-se** [comment]
I'm guessing you are using Shiny, then you can code it yourself, it's easy: [link1](https://shiny.rstudio.com/reference/shiny/latest/downloadHandler.html), [link2](https://community.rstudio.com/t/r-shiny-to-download-xlsx-file/18441/4).

**Comment by glin** [comment]
Hi, this isn't possible today, but similar features have been requested before (https://github.com/glin/reactable/issues/11, https://github.com/glin/reactable/issues/182). I'll group this together with those. In the meantime, I think Shiny is the way to go, as @algo-se mentions. Or if you have an existing Excel file of the raw data, you could add a hyperlink to that file (example in https://github.com/glin/reactable/issues/182#issuecomment-913069246).

**Comment by glin** [comment]
This is now possible to do without Shiny using the new JavaScript API in the development version (0.2.3.9000). See https://github.com/glin/reactable/issues/11#issuecomment-962809291 for more details and examples.

You can download the table data as a CSV file (not an XLSX file), which I guess is close enough to being Excel format. If you do need the ability to export an XLSX file, feel free to reopen this issue.
