### ISSUE TITLE
Multiple row selection is possible in single row selection mode with search or filter.

### ISSUE THREAD

**Issue by daeyoonlee** [glin/reactable#212]
![image](https://user-images.githubusercontent.com/68131229/142095262-c6ff91a6-0a8a-4539-8080-28ab24c648c7.png)

Thanks for the wonderful package.
I found an issue that is reproduced in the demo app as well.

1) enable search or column filter
2) enable row selection : single
3) select row
4) Input search condition that existing selections are not included.
5) select row -> **multiple row call back**
6) clear search -> **previous selection remains**

**Comment by glin** [comment]
Thanks for the report! It's fixed in https://github.com/glin/reactable/commit/e512178de0972733f5c2b808f53d2177e6e7cb6e. I didn't add a NEWS item since this only affected 0.2.3.9000.

**Comment by daeyoonlee** [comment]
thank you
