### ISSUE TITLE
Table disappears after updateReactable

### ISSUE THREAD

**Issue by daeyoonlee** [glin/reactable#213]
Thanks for the great package.
I am really enjoying using this.
I have updated issues.

1) Table disappears(js error), when a nonexistent row is specified as the `selected =`.
 -> It would be better to automatically `selected = NA`, rather than disappearing the table.

2) Table disappears(js error), when max-row of update df is less than selected row of existing df.
 -> In this case, `selected = NA` does not solve it, and it is solved only by re-rendering or `updateReactable` twice like below code. I guess that this problem is caused by trying to update the value first while maintaining the existing selected when updating.

```
library(shiny)
library(reactable)

ui <- fluidPage(
  reactableOutput(outputId = "table"),
  actionButton(inputId = "empty", label = "update")
)

server <- function(input, output, session) {
  
  output$table <- renderReactable(
    reactable(
      data = iris,
      selection = "single",
      defaultSelected = 3
    )
  )
  
  observeEvent(
    eventExpr = input$empty,
    handlerExpr = {
      
      # add this before update  
      updateReactable(
        outputId = "table",
        selected = NA
      )
      
      updateReactable(
        outputId = "table",
        data = iris[1:2,],
        selected = 2
      )
    }
  )
}

shinyApp(ui, server)
```

**Comment by glin** [comment]
Thanks again @daeyoonlee! Should be fixed in https://github.com/glin/reactable/commit/b26032826114f35fb594c504fcc7257098348b43.

**Comment by daeyoonlee** [comment]
Thanks for the update.  If updatereactable doesn't have a selected argument, it seems to delete the existing selected (even if it's not a js error situation). was that intended?

**Comment by daeyoonlee** [comment]
Thanks for the update.
