### ISSUE TITLE
Question : How to add title tag to all headers and columns.

### ISSUE THREAD

**Issue by daeyoonlee** [glin/reactable#221]
Thanks for the wonderful package.

I am looking for a way to add a title to all cells. It works by below code, but we want the tag not to appear in the title if the cell has a tag.
I've tried regular expressions from Google `cellInfo.value.replace(/(<([^>]+)>)/ig, '')`, but it doesn't work. 
Can you give me some advice?

![image](https://user-images.githubusercontent.com/68131229/148230455-dc69aca8-8e1c-48e0-bfb3-7b4035094e9c.png)

```
library(shiny)
library(reactable)

ui <- fluidPage(
  reactableOutput(outputId = "table")
)

server <- function(input, output, session) {
  
  df <- iris
  df[1,1] <- paste0("<div style='color:red'>",df[1,1],"</div>")
  
  output$table <- renderReactable(
    reactable(
      data = df,
      defaultColDef = colDef(
        html = TRUE,
        cell = JS("
          function(cellInfo) {
            return '<div title=\"' + cellInfo.value + '\">' + cellInfo.value + '</div>'
          }
        "),
        header = JS("
          function(colInfo) {
            return '<div title=\"' + colInfo.column.name + '\">' + colInfo.column.name + '</div>'
          }
        ")
      )
    )
  )
}

shinyApp(ui, server)
```

**Comment by glin** [comment]
I'd recommend either separating the styling from the cell rendering, or building the entire HTML string in the cell render function. Having HTML in the raw data makes it hard to get the original data values, and also interferes with things like sorting and filtering. I bet there is some way to get the original value using some regex replacement, but it's probably not worth the trouble.

Here's a minimal example of doing cell rendering and styling separately:
```r
library(reactable)

reactable(
  iris,
  defaultColDef = colDef(
    html = TRUE,
    cell = JS("
      function(cellInfo) {
        return '<div title=\"' + cellInfo.value + '\">' + cellInfo.value + '</div>'
      }
    "),
    style = "color:red"
  )
)
```

And another example of constructing all the HTML in the render function:
```r
library(reactable)

reactable(
  iris,
  defaultColDef = colDef(
    html = TRUE,
    cell = JS("
      function(cellInfo) {
        return '<div style=\"color:red\" title=\"' + cellInfo.value + '\">' + 
          cellInfo.value + '</div>'
      }
    ")
  )
)
```

If the styling or rendering has to be conditional based on the data, there are other examples for that in the docs, like at [Conditional Styling](https://glin.github.io/reactable/articles/conditional-styling.html).

**Comment by daeyoonlee** [comment]
Thanks for your kind reply. I agree with the comments that raw data should not have HTML.
