### ISSUE TITLE
paginateSubRows still not available in version 0.2.3.9000

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [glin/reactable#226]
Hi,

As titled.

This argument is still not available as stated in the change log.
I wonder if it is still unreleased.

Best,
Che-Wei

**Comment by glin** [comment]
Hi, 0.2.3.9000 isn't released on CRAN yet, so you'll have to install it from GitHub for now. Sorry if that was confusing in the change log. I'll look into marking it as "(unreleased)" in the NEWS to prevent future confusion.
