### ISSUE TITLE
Looking for a pretty way to create expandable rows for columns with a lot of text

### ISSUE THREAD

**Issue by sol-libesman** [glin/reactable#229]
I was hoping to make a table that has expandable rows that may stay open when toggled.

I wanted to put the columns with long amounts of text as expandable row details. The problem is when I use "details" in reactable to expand that column it's so wide that it goes off-screen making it hard to read. Is there a way to limit the max-width of the expandable row so it only expands approximately where the column is located?

```
library(reactable)
library(tidyverse)
library(shiny)
library(tippy)

library(htmltools)
library(webshot)
library(htmlwidgets)

iris2 <- cbind(USArrests[1:32,], mtcars, iris[1:32,])

data2 <-  iris2 %>%
  mutate(Species = 'This text is long and should only show up entirely when hovering because it is making the shape of my table ugly
                    and difficult to read when expanded. This text is long and should only show up entirely when hovering because it 
                      is making the shape of my table ugly and difficult to read when expanded.This text is long and should only show
                      up entirely when hovering because it is making the shape of my table ugly and difficult to read when expanded. 
                      This text is long and should only show up entirely when hovering because it is making the shape of my table ugly 
                      and difficult to read when expanded.') 

data <- data2 %>% mutate(Species = word(data2$Species, start =1, end=8, sep = fixed(" ")))

dog2 <- reactable( data,
                   columns = list(
                     Species = colDef(details = function(index) {
                       paste(data2[index, "Species"])
                     })),
                   striped = TRUE,
                   bordered = TRUE)

saveWidget(dog2, "test.html")
```
![image](https://user-images.githubusercontent.com/54593594/155263990-a6f31ac6-9c79-419b-9884-3524d442ab64.png)

Any help would be much appreciated! Apologies if this is a stupid question I've spent so much time trying to figure it out. I also tried css styling overflow: scroll. But I am not compotent enough to get it to work!  Thank you!

**Comment by daeyoonlee** [comment]
An alternative might be to wrap the cell contents in a DIV. For example <div style="max-height:100px; overflow: auto>cell contents<div>

**Comment by sol-libesman** [comment]
@daeyoonlee  Amazing thank you for the advice it is much appreciated! Would it be too bold to ask for an example? I've tried a bunch of things but couldn't get it to work (I'm sure my attempts don't make much sense) e.g., this was one attempt:
```
library(reactable)
library(tidyverse)
library(shiny)
library(tippy)

library(htmltools)
library(webshot)
library(htmlwidgets)

iris2 <- cbind(USArrests[1:32,], mtcars, iris[1:32,])

data <-  iris2 %>%
  mutate(Species = 'This text is long and should only show up entirely when hovering because it is making the shape of my table ugly
                    and difficult to read when expanded. This text is long and should only show up entirely when hovering because it 
                      is making the shape of my table ugly and difficult to read when expanded.This text is long and should only show
                      up entirely when hovering because it is making the shape of my table ugly and difficult to read when expanded. 
                      This text is long and should only show up entirely when hovering because it is making the shape of my table ugly 
                      and difficult to read when expanded.') 



dog2 <- reactable( data,
                   columns = list(
                     Species = colDef(
                     
           cell = JS("function(cellInfo) {
        const species = cellInfo.row['species'] || 'Unknown'
        return (
          '<div>' +
          '<div style=\"font-weight: 600\">' + cellInfo.value + '</div>' +
          '<div style=\"font-size: 12px\">' + species + '</div>' +
          <div style=\"max-width: 300px; overflow: auto>cell contents + <div> +
          '</div>'
          
        )
      }"),
                     html = TRUE
                   )),
                   striped = TRUE,
                   bordered = TRUE)
           
           
dog2

```

**Comment by glin** [comment]
This is a hard question, and probably more of a general design problem of how you present data with large amounts of text on a page. 

The row details might work well if there weren't so many columns to horizontally scroll through. Is it possible to reduce the number of columns or condense them somehow? When I have a table with too many columns, I often cut it down to just the essential columns with non-essential columns hidden away in row details, or combine multiple columns into one cell where it makes sense. For example:
- The CRAN Packages demo hides away a bunch of non-essential extra info in its row details, in a card/list-style format: https://glin.github.io/reactable/articles/cran-packages/cran-packages.html
- The Popular Movies demo combines movie title, URL, rating, genre, and runtime (5 different columns) into one to save on real estate: https://glin.github.io/reactable/articles/popular-movies/popular-movies.html. And a similar example at https://glin.github.io/reactable/articles/cookbook/cookbook.html#show-data-from-other-columns.

If not, limiting the max-width of the expandable row details is definitely possible, and showing it closer to the column would be sort of possible but not great. I think you were already on the right track with @daeyoonlee's suggestion of wrapping content in a div with custom styles. `max-width` would be the way to go for that. For showing the text closer to the column, there's not a good way to know where exactly a particular column is located. The row details pane is just a row that spans the entire table. But if expandable column is always at the end, you could align the row details content to the right so it shows up near the last column. This would still be kind of odd, so I'd still suggest reducing columns or exploring other ways of presenting the data.

Here's a quick example of this. I set `max-width` of the text to `700px`, added some padding for readability, and pushed the text to the end with `margin-left: auto`.
```r
dog2 <- reactable(
  data,
  columns = list(
    Species = colDef(details = function(index) {
      htmltools::div(
        style = "max-width: 700px; padding: 12px; margin-left: auto",
        paste(data2[index, "Species"])
      )
    })),
  striped = TRUE,
  bordered = TRUE
)

dog2
```
![table with row details limited to a max width and aligned to the right](https://user-images.githubusercontent.com/20401866/155862865-74cdcd46-e18e-4f83-9419-5c7be7f89ac2.png)
