### ISSUE TITLE
Initial expanded rows

### ISSUE THREAD

**Issue by jienagu** [glin/reactable#23]
Hi @glin ,

Congratulations on your wonderful R package!! I am a big fan of your package now! I really like the features that we can have the rows collapsible with adding `detail()`. I have one questions that if there is a way to default the rows as expanded initially so users can see all details without clicking each rows? 

Thanks!

**Comment by glin** [comment]
Hi, thanks for the suggestion. Would you like to have all rows expanded at once -- something like `reactable(defaultExpanded = TRUE)` -- or the ability to select which rows are expanded? Either way is possible, but implementing the latter might get pretty complicated.

**Comment by jienagu** [comment]
Hi @glin , thanks for giving me suggestions! The first option (`reactable(defaultExpanded = TRUE)`) should be good enough. Is `defaultExpanded ` already a parameter in the reactable package? Thanks again!

**Comment by glin** [comment]
I've added a `reactable(defaultExpanded = TRUE)` option to the development version on GitHub. Check out https://glin.github.io/reactable/articles/examples.html#default-expanded-rows for an example, and let me know if you run into any issues.

**Comment by jienagu** [comment]
Wow!!! That works like a magic! Thanks for adding it! I appreciate your help! This is an AMAZING package!

**Comment by zdenkoG** [comment]
Hi @glin !

 I am amazed with package too; it is really great! :) 
But it would be also great if it would be possible to expand just single row… Thanks!!
