### ISSUE TITLE
Aggregate function across columns

### ISSUE THREAD

**Issue by dysonsphere-startmail** [glin/reactable#230]
Is there a way to define the aggregate by a function that takes data from other columns?
For example: 
Can the aggregate data for col3 be `((aggregate of col1)*(a value)/(aggregate of col2))` ?

**Comment by lukr90** [comment]
same question [here](https://stackoverflow.com/questions/71234458/creating-custom-rendered-footer-values-i-a-reactable)

**Comment by glin** [comment]
Yes, you can write your own custom aggregate function in JavaScript to do this:

> Custom aggregate functions are useful when none of the built-in aggregate functions apply, or when you want to aggregate values from multiple columns. For example, when calculating aggregate averages or percentages.

Check out the [Custom aggregate function docs](https://glin.github.io/reactable/articles/examples.html#custom-aggregate-function) for more details and an example.

**Comment by lukr90** [comment]
And in addition is it possible to access the values in other columns using the rows argument for Footers also?

**Comment by glin** [comment]
@lukr90 Yes, see the [Footers - JavaScript render function documentation](https://glin.github.io/reactable/articles/custom-rendering.html#footers-js-render-function). I don't think there are any examples of custom footer renderers that aggregate values from multiple columns, but here's an example of a footer that accesses values from its own column: https://glin.github.io/reactable/articles/examples.html#javascript-render-function-1. Each row data object in `colInfo.data` contains the values for other columns as well.

**Comment by lukr90** [comment]
would you mind giving a short example of how to access the row data object in `colInfo.data` to use values for other columns?

**Comment by glin** [comment]
@lukr90 Sure, here's a quick example of a footer render function that uses `colInfo.data`. It's like the custom aggregate function example in the docs, except `colInfo.data` takes the place of `rows`.

```r
library(reactable)
library(dplyr)

set.seed(10)

data <- sample_n(MASS::Cars93[23:40, ], 30, replace = TRUE) %>%
  mutate(Price = Price * 3, Units = sample(1:5, 30, replace = TRUE)) %>%
  mutate(Avg.Price = Price / Units) %>%
  select(Model, Manufacturer, Price, Units, Avg.Price)

reactable(
  data,
  groupBy = "Manufacturer",
  columns = list(
    Price = colDef(aggregate = "sum"),
    Units = colDef(aggregate = "sum"),
    Avg.Price = colDef(
      # Calculate the aggregate Avg.Price as `sum(Price) / sum(Units)`
      footer = JS("function(colInfo) {
        let totalPrice = 0
        let totalUnits = 0
        colInfo.data.forEach(function(row) {
          totalPrice += row['Price']
          totalUnits += row['Units']
        })
        return (totalPrice / totalUnits).toFixed(2)
      }")
    )
  )
)
```
