### ISSUE TITLE
grouped in colDef is missing

### ISSUE THREAD

**Issue by aavanesy** [glin/reactable#231]
Version 0.2.3

I still see it here
https://glin.github.io/reactable/reference/colDef.html

But locally

![image](https://user-images.githubusercontent.com/48486871/156916318-cb621169-e697-4186-b433-cc87f276774b.png)

![image](https://user-images.githubusercontent.com/48486871/156916310-4e13578a-50df-4d80-b5ca-70d196c6e240.png)

**Comment by glin** [comment]
The `grouped` argument was only added in the latest development version (v0.2.3.9000), so you'll have to install reactable from GitHub to use it. Unreleased features are usually called out in the docs (e.g., the [Grouped cell rendering examples](https://glin.github.io/reactable/articles/examples.html#grouped-cell-rendering)), but it looks like these notes are missing from the Reference section. I'll look into marking unreleased features in the Reference section to prevent future confusion.
