### ISSUE TITLE
Is it possible to set semicolon instead of comma in Reactable.downloadDataCSV as column separator

### ISSUE THREAD

**Issue by novotny1akub** [glin/reactable#239]
I would like to ask if it is possible to set semicolon instead of comma in Reactable.downloadDataCSV as a column separator. Similarly, I would like to set comma instead of dot for the decimal mark. Looking at the code of Reactable.downloadDataCSV, it does not seem to be possible. I was just wondering if I can replace Reactable.downloadDataCSV with my own function. Any help is appreciated.

**Comment by glin** [comment]
Neither of these are possible at this time, and I've tagged this as a feature request.

You can replace `Reactable.downloadDataCSV` with your own function though. Check out [`Reactable.getState()` in the JavaScript API](https://glin.github.io/reactable/articles/javascript-api.html#reactable-getstate), which lets you get the raw table data to do whatever you want with it.

**Comment by radovan-miletic** [comment]
Just when I needed it most. Thank you @novotny1akub !
As I'm working with Portuguese characters, I have added minor changes to one line of your code:   

````
var blob = new Blob(['\uFEFF'+csv], { type: 'text/csv;charset=utf-8;' });
````  

It might help those with UTF-8 encoding issues (picked from [here](https://stackoverflow.com/questions/31959487/utf-8-encoidng-issue-when-exporting-csv-file-javascript)).

**Comment by glin** [comment]
It's now possible to use a custom field separator and decimal separator in the development version:

> * [`Reactable.downloadDataCSV()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-downloaddatacsv) in the JavaScript API now supports an additional `options` argument to change the field or decimal separator, include specific columns, and exclude column headers. ([#239](https://github.com/glin/reactable/issues/239), [#293](https://github.com/glin/reactable/issues/293))
> * New [`Reactable.getDataCSV()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-getdatacsv) method in the JavaScript API to get the table data as a CSV string.

You can change the separators using the `options` argument like:
```js
Reactable.downloadDataCSV('cars-table', 'cars93.csv', { sep: ';', dec: ',' })
```
There's also a new `Reactable.getDataCSV()` method to just get the raw CSV string, in case you want to implement your own downloader or send the CSV back to Shiny or whatever.

I didn't totally understand the encoding issues, so you can open a new issue with details if that's still a problem.
