### ISSUE TITLE
support for changing the language of the user interface of `reactable`

### ISSUE THREAD

**Issue by Leo-Lee15** [glin/reactable#24]
Hi, 

Thanks for writing such an awesome package!

As a Chinese user, I think it would be useful if the package could support setting the language of user interface of `reactable` just like the `DT` package.

Here is a [nice example](https://rstudio.github.io/DT/004-i18n.html) from the `DT` package. 

![image](https://user-images.githubusercontent.com/18102092/71520614-fcb56180-28f7-11ea-82c2-73aa9c3453e0.png)

**Comment by glin** [comment]
Hi, thanks for the suggestion. Agreed that this would be useful, and it'll probably be one of the next things I work on. I don't know if there will be translations like in DataTables, but there will definitely be a way to customize text and labels in the table for different locales.

**Comment by glin** [comment]
There's now basic support for customizing the language strings in the development version: https://glin.github.io/reactable/reference/reactableLang.html

Here's one example: https://glin.github.io/reactable/articles/examples.html#language-options

And another of a partial Chinese translation, based on the DataTables translation:
https://glin.github.io/reactable/articles/internationalization.html

```r
reactable(
  iris[1:30, ],
  searchable = TRUE,
  showPageSizeOptions = TRUE,
  language = reactableLang(
    searchPlaceholder = "搜索",
    searchLabel = "搜索",
    noData = "没有匹配结果",
    pageSizeOptions = "显示 {rows}",
    pageInfo = "{rowStart} 至 {rowEnd} 项结果，共 {rows} 项",
    pagePrevious = "上页",
    pageNext = "下页",
    # The previous/next page button text is descriptive enough, don't need additional labels
    pagePreviousLabel = "",
    pageNextLabel = ""
  )
)
```

[![reactable Chinese translation example](https://user-images.githubusercontent.com/20401866/74598410-bb5b4b80-5036-11ea-96a9-59ecb43e5df2.png)](https://glin.github.io/reactable/articles/internationalization.html)

**Comment by Leo-Lee15** [comment]
Thanks a lot!
