### ISSUE TITLE
Is it possible to use `dangerouslySetInnerHTML` in JS function?

### ISSUE THREAD

**Issue by gsmolinski** [glin/reactable#242]
MRE:

```
library(htmltools)
library(reactable)

reactable(iris, columns = list(
  Species = colDef(
    cell = function(value) {
      tags$span(dangerouslySetInnerHTML = list("__html" = as.character(tags$i(value))))
    }
  ))) # it works

reactable(iris, columns = list(
  Species = colDef(
    cell = JS("function(cellInfo) {
              value = '<i>' + cellInfo.value + '</i>';
              return (
              <span dangerouslySetInnerHTML={{__html: value}}></span>
              );
    }")
  ))) # it doesn't work
```

I don't know React and my experience with JS is very limited. It looks like the problem is with this line:

```
<span dangerouslySetInnerHTML={{__html: value}}></span>
```
Syntax error is returned - `expected expression, got '<'`. If I'm not wrong, the line above is valid in React, but not in JS.

What can I do to be able to use `dangerouslySetInnerHTML` with JS function? I have used R function with success, but I want to try if JS will be faster (with my R function I have noticed a lag with bigger table).

**Comment by glin** [comment]
It is possible, but the built-in raw HTML rendering option will be easier to use in most cases, `colDef(html = TRUE)`:

```r
reactable(iris, columns = list(
  Species = colDef(
    cell = JS("function(cellInfo) {
              return '<i>' + cellInfo.value + '</i>';
    }"),
    html = TRUE
  )
))
```
Also see some examples in the [Custom Rendering - JavaScript render function examples](https://glin.github.io/reactable/articles/examples.html#javascript-render-function).

In the rare case that you do need `dangerouslySetInnerHTML` in a JS function though, you'll have to return a React element from the function using `React.createElement()`:
```r
reactable(iris, columns = list(
  Species = colDef(
    cell = JS("function(cellInfo) {
              value = '<i>' + cellInfo.value + '</i>';
              return React.createElement('span', {
                dangerouslySetInnerHTML: { __html: value }
              });
    }")
  )
))
```

**Comment by gsmolinski** [comment]
Thank you! I'm using `dangerouslySetInnerHTML`, because I don't want to target all cells as in some cells may be HTML which I want to leave escaped - my intention is to display source code (in Shiny app) and make syntax highlighter, so I don't want to touch cells where I guess may be HTML (I suppose `HTML = TRUE` is a global flag for all cells in column).
