### ISSUE TITLE
incorrect columnGroups alignment under Shiny when column is hidden

### ISSUE THREAD

**Issue by Patrikios** [glin/reactable#253]
In shiny app, if I hide a column, the grouping header is not correctly alligned, it becomes padded to a side.  This is an issue when running under shiny, in vanilla reactable output from RStudio console it is not present.
In the reprex when you set  `vs = colDef(show = TRUE)` the problem disapears.

Reprex:

```
library(shiny)
library(reactable)
shinyApp(
  ui = reactableOutput("react"),
  server = function(input, output) {
    output$react <- renderReactable(
      reactable(mtcars,
        columnGroups = list(
          colGroup(
            name = "Group A",
            columns = c("mpg", "cyl"),
            align = "center"
          ),
          colGroup(
            name = "Group B",
            columns = c("drat", "wt", "qsec"),
            align = "center"
          ),
          colGroup(
            name = "Group C",
            columns = c("carb"),
            align = "center"
          )
        ),
        columns = list(
          vs = colDef(show = FALSE)
        ),
        bordered = TRUE,
        theme = reactableTheme(
          borderColor = "black",
          borderWidth = 2L
        )
      )
    )
  }
)
```

Sample output on my mascihne:
![image](https://user-images.githubusercontent.com/11005155/177964928-5f0d9962-0596-4ed3-9f7f-42e46d23202c.png)

R version 3.6.3 (2020-02-29)
shiny 1.7.1
reactable 0.3.0.9000

**Comment by glin** [comment]
Thanks for the bug report! The column group header width calculation wasn't accounting for hidden columns at all. It should now be fixed in the latest development version, 0.3.0.9000 (https://github.com/glin/reactable/commit/ce2d3c033271e8734d722d545017e6411da4f82d):

> * Column group header widths are now calculated correctly with hidden columns
  in the column group (@Patrikios, [#253](https://github.com/glin/reactable/issues/253)).
