### ISSUE TITLE
Internet Explorer 11 problem with Twitter Followers example

### ISSUE THREAD

**Issue by superboreen** [glin/reactable#27]
The Twitter Followers example is not rendering correctly for me in Internet Explorer 11. Just wondering if this is due to my IE configuration or location (being behind a corporate firewall), or is happening for other people too.

**Comment by glin** [comment]
Thanks for pointing this out. The Twitter Followers example wasn't originally made with IE11 in mind, and used some JavaScript features that don't work in IE11 (template literals). I've tweaked it to be compatible with IE11 in https://github.com/glin/reactable/commit/fecf4ceca2d7e059d08540ba2497f9f9c72586c4 -- could you check if it works now?

**Comment by superboreen** [comment]
Thanks for fixing it. Means a lot to me. Looks good in Edge. Will check IE11 on Monday when I'm back behind the firewall.

**Comment by superboreen** [comment]
I just checked that in IE11. Looks fine. Thanks.
