### ISSUE TITLE
How to make some rows selected at default?

### ISSUE THREAD

**Issue by ShixiangWang** [glin/reactable#279]
Hi,

I want to show a table with some rows selected at default in Shiny. I cannot find usage about that, is it possible?

Best,

Shixiang

**Comment by glin** [comment]
Hi, you can use the `reactable(defaultSelected = ...)` argument for that. There's an example in the docs at [Default selected rows](https://glin.github.io/reactable/articles/examples.html#default-selected-rows).

**Comment by ShixiangWang** [comment]
@glin Great, thank you :)
