### ISSUE TITLE
Suggestion: `renderReactable()` should work when provided a dataframe

### ISSUE THREAD

**Issue by daattali** [glin/reactable#289]
When I want to use a pretty table in a shiny app, I like to use {reactable}. If I want to use a customized `reactable()`, then it makes sense for me to explicitly make a call to `reactable()` with all the right parameters. But sometimes I just want a quick and easy table, and it would be great if the following worked:

```r
library(shiny)

ui <- fluidPage(
  reactable::reactableOutput("table")
)

server <- function(input, output, session) {
  output$table <- reactable::renderReactable({
    mtcars
  })
}

shinyApp(ui, server)
```

**Comment by glin** [comment]
This is an interesting idea, and I had considered it before but decided not to do it. I liked the convenience of doing `DT::renderDT(data)`, but also found it confusing when I was learning DT way back. There also aren't any widgets besides DT I can think of that support something like this, and think DT is more like the exception.

So I'd rather support just one consistent way of rendering widgets, and if you do want a shortcut, you could possibly create your own render function wrapper. (probably pointless for one-off apps though)
```r
library(shiny)

ui <- fluidPage(
  reactable::reactableOutput("table")
)

renderReactable <- function(x) {
  reactable::renderReactable(if (is.data.frame(x)) reactable::reactable(x) else x)
}

server <- function(input, output, session) {
  output$table <- renderReactable({
    mtcars
  })
}

shinyApp(ui, server)
```

And the other catch is that this would complicate the `renderReactable()` implementation a bit, as Shiny's built-in async support assumes your promise returns an HTML widget. If not, you'll have to do a little hoop jumping to catch the promise that returns a data frame and then convert that to a reactable widget. So the `renderReactable()` wrapper above wouldn't work with promises without some more modification.

There might be other tricky bits I'm not thinking of as well, but this is already complicated enough that I don't think it's worth doing for a niche case to save some typing. 

If the data isn't reactive, you could also skip the Shiny part and just render a static widget:
```r
library(shiny)

ui <- fluidPage(
  reactable::reactable(mtcars)
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```
