### ISSUE TITLE
set delimiter via Reactable.downloadDataCSV

### ISSUE THREAD

**Issue by nick-youngblut** [glin/reactable#293]
The CSV file format cause problems in many countries, since semi-colon is often used instead of comma. So, it would be very helpful to have the option of setting the delimiter for `Reactable.downloadDataCSV` so that one can export as TSV. For example: `Reactable.downloadDataCSV('cars-table', 'cars93.csv', sep='\t')`

**Comment by glin** [comment]
There have been a couple related feature requests (https://github.com/glin/reactable/issues/239), so I've now added this plus a few more CSV options to the development version:

> * [`Reactable.downloadDataCSV()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-downloaddatacsv) in the JavaScript API now supports an additional `options` argument to change the field or decimal separator, include specific columns, and exclude column headers. ([#239](https://github.com/glin/reactable/issues/239), [#293](https://github.com/glin/reactable/issues/293))
> * New [`Reactable.getDataCSV()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-getdatacsv) method in the JavaScript API to get the table data as a CSV string.

You can change the separator using the `options` argument like:
```js
Reactable.downloadDataCSV('cars-table', 'cars93.csv', { sep: '\t' })
```
