### ISSUE TITLE
`updateReactable` converts numeric `NA` to zeros

### ISSUE THREAD

**Issue by msaltieri** [glin/reactable#296]
Hello @glin, thanks for the nice package.

I've been using **reactable** for a long time but I've never realized this weird behavior. Basically when a `reactable` is updated via `updateReactable`, all the numeric `NA`s are replaced with zeros. Please find below a reprex.

```
library(reactable)
library(shiny)

# PARAMETERS ----
update_time <- 5 # seconds

# UI ----
ui <- fluidPage(

    # Application title
    titlePanel("Reactable Update Example"),

    # Application body
    fluidRow(
        column(
            width = 12,
            reactableOutput("table")
        )
    )

)

# SERVER ----
server <- function(input, output) {

    # Updater
    updater <- reactiveVal(Sys.time())
    observe({
        invalidateLater(1000 * update_time)
        updater(Sys.time())
    })

    # Data
    data <- reactive(
        tibble(
            id = 1:5,
            x = rnorm(5),
            y = NA_real_
        )
    ) %>%
        bindEvent(updater())

    # Reactable
    observe(
        updateReactable(
            outputId = 'table',
            data = data()
        )
    )

    output$table <- renderReactable(
        reactable(
            data = isolate(data())
        )
    )

}

# APP ----
shinyApp(ui, server)
```

What I get, after the first update in 5 seconds, is this table:
<img width="1406" alt="Screenshot 2022-12-05 alle 15 44 20" src="https://user-images.githubusercontent.com/26568338/205665320-0c802d2e-a51d-4620-abc6-b5bb965c6583.png">

Am I missing some necessary configuration?

**Comment by glin** [comment]
Hi, that is weird indeed, and I can't reproduce it with either reactable 0.3.0 or the latest 0.4.1 version on CRAN. After waiting 5 seconds, my `y` column is still a column of blank cells.

What version of reactable are you running? Can you provide some `sessionInfo()` output? I did make some changes (bug fixes) around numeric NA handling recently though, so I wonder if this is a bug in some previous dev version.

**Comment by msaltieri** [comment]
Hi @glin, thanks for your feedback. I was using an old development version of reactable (0.3.0.9000). Now that I've updated to the new 0.4.1.9000 everything seems to be fixed. Thank you!
