### ISSUE TITLE
Add median as one of the built-in aggregate functions for colDef

### ISSUE THREAD

**Issue by mattwarkentin** [glin/reactable#30]
Hi @glin,

Wondering if it would be possible to add `median()` as a built-in `aggregate` function for `colDef()`? I know that the user can provide a custom `JS()` function to do this on their own, so I could probably dig up enough JS to get it working, but I think median would be nice to have as a built-in.

Actually, while I'm thinking of it, it would be nice to be able to pass R functions instead of/in addition to JS functions, if possible. That way one could pass the `median` function, or an anonymous function with some other aggregating capability. Thoughts?

**Comment by glin** [comment]
Hi,

Thanks for the suggestion. Calculating the median is pretty straightforward, so I went ahead and added a `"median"` aggregate function in https://github.com/glin/reactable/commit/86adb96945c04f36f31ecfa375f134796847d06b. For example:
```r
reactable(
  iris,
  groupBy = "Species",
  columns = list(Sepal.Length = colDef(aggregate = "median"))
)
```

Passing R functions would be really cool, and totally possible I think. There'd be limitations though. JS aggregate functions run on the fly and update with table changes. For example, the aggregated values update when you filter this table: https://glin.github.io/reactable/articles/examples.html#aggregated-cell-rendering. R aggregated values would have to be precalculated and never change. But it's pretty much the same trade-off as JS vs. R render functions - much easier to write custom aggregators as an R programmer. Thanks for that suggestion as well! I've added it to my to-do list, but feel free to file a separate issue for it.

**Comment by mattwarkentin** [comment]
Wow, thanks for the quick addition of the median!

Ahh yes, I didn't not think about how the JS functions update the table when it is modified. Well, perhaps an `R` function could still be passed with the knowledge that it cannot be dynamically updated once rendered. As you mention, this is just the standard expectation for any `R` vs. JS render functions. I can definitely think of some cool custom aggregators that I can write in `R` and wouldn't really know how to do in JS, only due to my own JS limitations.

Anyway, thanks for considering this! I will file its own issue.

**Comment by timelyportfolio** [comment]
Just a thought, but maybe we could build a helper library with something like [simple-statistics](https://simplestatistics.org/) to provide a fuller set of statistical functions calculated in JS but written so they would be accesssible to an R user.

**Comment by sanjmeh** [comment]
How can I check if any more R functions were added in the aggregator functions, if any. 
I know `median`, `mean` is there. I was looking for `first` and `last`
