### ISSUE TITLE
Provide the ability to use R functions as aggregators for colDef()

### ISSUE THREAD

**Issue by mattwarkentin** [glin/reactable#31]
See #30

**Comment by timelyportfolio** [comment]
Just a thought, but maybe we could build a helper library with something like simple-statistics to provide a fuller set of statistical functions calculated in JS but written so they would be accesssible to an R user.

**Comment by sanjmeh** [comment]
I am badly looking for more standard functions. Two simple functions (**first** and **last**) are what I need now (like difference of first and last) and I am trying to learn JS for it. Is there any progress on using R functions straight instead of JS?

**Comment by olivroy** [comment]
I think it would be great! I am trying to build the summary rows functiunality for gt tables, but I am having a hard time.

gt provides its `extract_summary()` function.

Could aggregate accept also a (static) value that could simply be computed outside of reactable and simply displayed?

https://github.com/glin/reactable/blob/22ccffca5c3455e8f5689f9f5c26d9fefd0693d2/R/server-df.R#L187-L220

https://github.com/rstudio/gt/issues/1359
