### ISSUE TITLE
column name style?

### ISSUE THREAD

**Issue by MayaGans** [glin/reactable#32]
Hi! I absolutely LOVE this package it's amazing thank you! I was wondering how I would use the style argument if I wanted to change the color of the column name (ie Sepal.Width == "red")? Thanks again!

**Comment by glin** [comment]
Hi, you can style headers using the `headerStyle` and `headerClass` arguments on `colDef()`:
```r
reactable(
  iris,
  columns = list(
    Sepal.Width = colDef(headerStyle = list(color = "red"))
  ),
  # Or style all headers at once
  defaultColDef = colDef(headerClass = "header")
)
```

And I'll get some more examples added to the docs soon. I know they're pretty light on styling things besides regular table cells right now.
