### ISSUE TITLE
update pageSize value with javascript API

### ISSUE THREAD

**Issue by NedHermann** [glin/reactable#322]
I was messing with the `Reactable.getState()` function from the javascript API documentation and couldn't find a resource on updating the `pageSize` state property. ie. how to use the API to change the number of displayed rows (pageSize) from x to y. 

I have read the rest of the documentation which updates other things like hidden columns, filters, etc... and came across the R function `updateReactable()` but neither seems to answer my question...

Thanks.

**Comment by NedHermann** [comment]
Figured it out. The answer, along with many other functionalities, is in `.getInstance`.
```
const newPageSize = 50;
Reactable.getInstance('table').setPageSize(newPageSize);
```

**Comment by glin** [comment]
Yep, there's no support for updating the page size through the JavaScript API at the moment. You can definitely do it using `getInstance().setPageSize()`, but that's undocumented/internal so use at your own risk and double check that it still works on version upgrades.

This should be really simple to add to the JavaScript API though, and I could see it as a useful way to create your own pagination controls (along with prev/next page, go to page N).

**Comment by NedHermann** [comment]
Ah, I have a few other uses from the `getInstance()` that would be great to see supported eventually as well:

Case:
I want a table that can save filters to be applied later. It would save selected rows, which columns are being sorted, which columns are visible, and any other value that was being filtered with the `filterMethod`. 
 - Functions:
   - `Reactable.getInstance('tbl').setRowsSelected()` I am using this to apply the selected rows from the saved filter
   - `Reactable.getInstance('tbl').setSortBy()` I am using this to apply the column sort from the saved filter
   
Thanks.

**Comment by glin** [comment]
This is now in the development version:

> * New [`Reactable.gotoPage()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-gotopage)  and [`Reactable.setPageSize()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-setpagesize) methods in the JavaScript API to change the current page or set the current page size. ([#322](https://github.com/glin/reactable/issues/322))

`setSortBy()` is already on the roadmap (https://github.com/glin/reactable/issues/316) and will probably be done soon-ish. `setRowsSelected()` would probably be another straightforward addition - can add that as well.

**Comment by glin** [comment]
And sorting is now added as well:

> * New [`Reactable.toggleSortBy()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-togglesortby) and [`Reactable.setSortBy()`](https://glin.github.io/reactable/articles/javascript-api.html#reactable-setsortby) methods in the JavaScript API to programmatically control column sorting. `toggleSortBy()` toggles sort on a single column (cycling between ascending and descending), while `setSortBy()` sets the full sort state declaratively. Also available via `updateReactable(sortBy = ...)` in Shiny. ([#316](https://github.com/glin/reactable/issues/316), [#322](https://github.com/glin/reactable/issues/322))
