### ISSUE TITLE
Error with list column - C stack usage is too close to the limit

### ISSUE THREAD

**Issue by soetang** [glin/reactable#333]
Hey 

I am not sure if this is the correct place for the issue we are encountering.

List columns created using vctrs::list_of fails to render with reactable and throws an error. We experience the problem when reading data.frames from parquet files using the arrow package. 

```r
test_df <- tibble::tibble(
  hej = vctrs::list_of(c("hej3", "hej2"), c("kanin", "træ"))
)

reactable::reactable(test_df)
```
leads to: 
Error: C stack usage  7977152 is too close to the limit

reactable: version 0.4.4
vctrs: version 0.6.3

Overwriting the class of the column - fixes the issue. However, this does not feel like a good solution:

```r
class(test_df$hej) <- 'list'
reactable::reactable(test_df)
```

**Comment by glin** [comment]
Hi, that's odd and I can't reproduce this using that code. Is that the exact code that reproduces the issue, or is it a simplified version?

**Comment by soetang** [comment]
Hey - Yes for me the exact code reproduces the issue for me (although yes I made it from at larger version). I will try to do some more testing of scenarios.

If i run the code interactively  or in a shiny dashboard it fails. However t worked when running it within the reprex package. I will try to create some more specific examples.
