### ISSUE TITLE
reactable - dataListFilter not working - error - colDef: unused argument!

### ISSUE THREAD

**Issue by pswaminath** [glin/reactable#338]
Hi, 
I am using reactable and displaying a dataframe with few columns. I have a column called conditions where I used dataListFilter for autocomplete feature. (https://glin.github.io/reactable/articles/custom-filtering.html)

I have made the necessary changes by looking at this post:
https://github.com/glin/reactable/issues/266

I am able to see the dataListFilter working on my **local Rstudio** but when **testing on shiny server**, I get the following error.

**Error in colDef: unused argument (filterInput = dataListFilter("browtable"))**

I am on R 4.2.1 and reactable version (reactable_0.2.3) on shiny server. 

**Will this dataListFilter feature not work on this reactable version?**

What could be the reason? Please suggest as how this error could be solved. 
Thank you.

PS

**Comment by glin** [comment]
Hi, `filterInput` was added in reactable 0.3.0 so you'll have to upgrade to at least that version: https://glin.github.io/reactable/news/index.html#reactable-030

**Comment by pswaminath** [comment]
Hi, 
Thanks for your response. I upgraded to reactable 0.4.4 and it works. Thank you.

PS
