### ISSUE TITLE
Header can not be fixed on chrome

### ISSUE THREAD

**Issue by taiwankyh** [glin/reactable#372]
I use the reactable package version 0.4.4, 
               htmltools package version  0.5.7
               htmlwidgets package version 1.6.4

I create a table, as
 data %>% reactable (...)

It looked well and the header fixed at the Rstudio viewer panel. However, once it was saved and I use chrome (ver 版本 124.0.6367.61 (正式版本) (64 位元)) to open it. The header was not fixed. Because the table is desinged as expandable, and it was too inconvenient for no fixed header.

Could you please help me, thanks a lot. 

Kuo Yao-Hung

**Comment by glin** [comment]
Hi, this may have been an issue with very old Chrome versions, but I can't reproduce now on Chrome 124 with those same package versions. Do you see the sticky header working in this example? https://glin.github.io/reactable/articles/examples.html#no-pagination

Otherwise can you post your full table code? Maybe there's something special about the styling there.

**Comment by taiwankyh** [comment]
Dear Greg

Thanks for your reply, and it worked after adding (height = 500).
I think it is not necessary for assign the height and the header goes down
when full-screen.
It is really nice to receive your help. I really like reactable package,
and it is very very easy to use.

Best regards,

Kuo Yao Hung

Greg Lin ***@***.***> 於 2024年4月22日 週一 上午10:28寫道：

**Comment by glin** [comment]
Yep, by default the table height is 100% of its parent element, so it'll fill the page if you don't set a fixed height on it. The sticky header will only work when there's a scrollbar in the table.

**Comment by taiwankyh** [comment]
Thanks so much, and I must appreciate your great work, {reactable} package
and your kindly help.


Greg Lin ***@***.***> 於 2024年4月29日 週一 上午11:19寫道：
