### ISSUE TITLE
Using polyfill

### ISSUE THREAD

**Issue by amkhosla** [glin/reactable#381]
The code for internationalization using polyfill needs to be updated. polyfill has been hijacked by a Chinese company .

https://thehackernews.com/2024/06/over-110000-websites-affected-by.html

**Comment by glin** [comment]
Thanks for the report. The internationalization code does not use the compromised polyfill.io service, so it's unaffected. It uses FormatJS's own polyfill implementation from a local file bundle, with pinned versions, e.g. https://formatjs.io/docs/polyfills/intl-locale#simple
