### ISSUE TITLE
dynamically show the code when toggle options in shiny

### ISSUE THREAD

**Issue by lz100** [glin/reactable#42]
How do I display the code that is been used to generate reactable dynamically when I choose different options for the reactable in shiny? Just like your this [demo](https://glin.shinyapps.io/reactable/), but I didn't find the source code. Would you mind sharing the code?

**Comment by glin** [comment]
Sure, the source code for the app is here: https://github.com/glin/reactable/tree/master/inst/examples/app

It's more of a complicated and manual process that first generates a `reactable()` expression, and then evaluates it. If you want an easier way of dynamically getting the code for something, I'd recommend using https://github.com/rstudio/shinymeta instead.

Here's a greatly simplified version of the demo app though, if it helps:
```r
library(shiny)
library(reactable)

ui <- fluidPage(
  checkboxGroupInput("options", "Options", c("Filterable", "Searchable")),
  reactableOutput("table"),
  verbatimTextOutput("code")
)

server <- function(input, output, session) {
  # Get the table options
  options <- reactive({
    list(
      filterable = "Filterable" %in% input$options,
      searchable = "Searchable" %in% input$options
    )
  })
  
  # Generate the unevaluated reactable() code
  code <- reactive({
    opts <- options()

    call <- bquote(reactable(
      iris,
      filterable = .(opts$filterable),
      searchable = .(opts$searchable)
    ))

    code <- gsub("\\n", "\n", deparse(call, control = "useSource"), fixed = TRUE)
    paste(code, collapse = "\n")
  })

  # Evaluate the reactable() code
  output$table <- renderReactable({
    eval(parse(text = code()))
  })

  output$code <- renderPrint({
    writeLines(code())
  })
}

shinyApp(ui, server)
```

**Comment by lz100** [comment]
Fantastic, thank you so much!
