### ISSUE TITLE
react tables not rendered in R notebook

### ISSUE THREAD

**Issue by smailmy** [glin/reactable#43]
Hi @glin 

the react tables are not rendered when I use R notebook instead of R markdown, is it just me or it is a bug (i'm using latest chrome version under mac OS catalina)

**Comment by glin** [comment]
Hi,

Is it the same issue as this one, when using a dark theme in RStudio? https://github.com/glin/reactable/issues/21

If so, you can install the latest development version from GitHub to get the fix.

If not, could you provide more details on what happens? For example, a screenshot, or if there are any error messages, and etc.

**Comment by smailmy** [comment]
Sorry, I wasn't precise enough, actually it renders in the editor pretty much like in #21 but not when I click the review button

Just a reminder: it works fine with knit button for R markdown file but in this case I need to recompile all the code

![image](https://user-images.githubusercontent.com/17691937/80171252-c3f57280-85e1-11ea-8bcf-7d5ed97563ff.png)


![image](https://user-images.githubusercontent.com/17691937/80171135-7da01380-85e1-11ea-9780-ce83c18f9722.png)

**Comment by glin** [comment]
Oh huh, this is so weird. I see it as well. It looks like the widget's HTML dependencies aren't being picked up properly.

For whatever reason, I can get the table to show up by manually attaching the html dependencies like this:
````r
```{r}
htmltools::tagList(
  reactR::html_dependency_react(),
  reactR::html_dependency_reacttools(),
  reactable::reactable(iris)
)
```
````

![image](https://user-images.githubusercontent.com/20401866/80176421-22a8f500-85be-11ea-8ac3-3952535a3aab.png)

There's a bug somewhere, but I have no idea where. I'll look into it and report back - thanks for reporting this.

**Comment by smailmy** [comment]
Thank you for this tip

**Comment by glin** [comment]
Here's a better workaround. All you need to do is wrap the HTML widget in a Shiny tag:
````r
```{r}
htmltools::tagList(
  reactable::reactable(iris)
)
```
````

Or you could re-alias `reactable()` in a hidden chunk at the top like:
````r
```{r, echo=FALSE}
reactable <- function(...) {
  htmltools::tagList(reactable::reactable(...))
}
```

```{r}
reactable(iris)
```
````
![image](https://user-images.githubusercontent.com/20401866/80283497-9988df80-86dd-11ea-8077-23b83477f8fb.png)

**Comment by Ifitrains** [comment]
I face similar problems using `bookdown`. However, your proposed solution for R Notebook does not work unfortunately. For the time being, I switched to `DT`, but would be happy if it will be also possible to implement `reactable` in `bookdown`.

**Comment by kmillage** [comment]
@glin I'm having the same issue trying to display reactable tables in a Rmarkdown report rendered from within a shiny app. 

I can get the table to display correctly in the following circumstances: 
- in the Rmarkdown preview
- in the Rstudio plot viewer when the document is rendered if you wrap the reactable call in print() 
- in the document when manually pressing "Knit" from within Rstudio

I've downloaded the development version and tried every combination of the approaches suggested in this thread. Any updates or other suggestions?
