### ISSUE TITLE
Update footer values based on filtered or selected rows

### ISSUE THREAD

**Issue by smailmy** [glin/reactable#44]
Hi @glin again,

I'm playing with your package and it's really a cool package with beautiful rendering

I'm wondering if there is way that footer values change based on filtered and/or selected rows?

Best,

**Comment by glin** [comment]
Hi,

Footer values based on filtered rows is possible if you use a custom footer renderer. For example: https://glin.github.io/reactable/articles/cookbook/cookbook.html#dynamic-totals-1. You'll just have to write some JavaScript.

Footer values based on selected rows is not possible today, but it's an interesting idea to consider for the future. Usually I'd expect to do something with selected rows outside of the table, but the footer could be a good place for that as well.

**Comment by smailmy** [comment]
Thanks a lot @glin , sorry didn't see that example and yes it would be nice to see selection works with footer

All the Best,
