### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by davelorino** [glin/reactable#45]
Hi, I am having an issue getting images to render, I have tried using the base example:

```
library(reactable)
library(htmltools)

data <- data.frame(
  Animal = c("beaver", "cow", "wolf", "goat"),
  Body = c(1.35, 465, 36.33, 27.66),
  Brain = c(8.1, 423, 119.5, 115)
)

reactable(data, columns = list(
  Animal = colDef(cell = function(value) {
    image <- img(src = sprintf("images/%s.png", value), height = "24px", alt = "alt")
    tagList(
      div(style = list(display = "inline-block", width = "45px"), image),
      value
    )
  }),
  Body = colDef(name = "Body (kg)"),
  Brain = colDef(name = "Brain (g)")
))

```

The table renders but the images don't, I get the broken image and alt text. The files are in the correct folder. 

I am using the github (not CRAN) version of reactable.

<img width="931" alt="Screen Shot 2020-05-14 at 1 28 51 pm" src="https://user-images.githubusercontent.com/18080930/81889529-10cbd800-95e7-11ea-93e6-bedd3d26a02b.png">

Thank you!

**Comment by glin** [comment]
Hi,

Tildes (~) are interpreted as normal tilde characters in URLs, and browsers don't expand them to the home directory. You'll have to use an absolute file path like `C:/Users/user/image.png` (Windows) or `/Users/user/image.png`.

However, these file paths will only work on your own computer. I recommend using relative URLs to the R Markdown document instead, like `images/image.png` (where `images/` is a directory alongside your Rmd file).

The relative URLs must work from the location of the rendered doc though. If you render to a custom output directory, I think you have to manually copy over the images to the output directory. R Markdown doesn't make it super easy to include external images like this.

With pkgdown, external files can be included by specifying a `resource_files` field in the YAML header: https://pkgdown.r-lib.org/reference/build_articles.html#external-files. That's what the reactable docs do, but it only works in pkgdown as far as I know.

Alternatively, you can embed images in the document using `knitr::image_uri`: https://rdrr.io/cran/knitr/man/image_uri.html

```r
reactable(data, columns = list(
  Animal = colDef(cell = function(value) {
    img_src <- knitr::image_uri(sprintf("images/%s.png", value))
    image <- img(src = img_src, height = "24px", alt = "")
    tagList(
      div(style = list(display = "inline-block", width = "45px"), image),
      value
    )
  })
))
```

This will convert the image to an embeddable data URI and work anywhere, on your computer or served on the web. Not recommended for large images though.

**Comment by davelorino** [comment]
Thank you for your reply, I am doing this with Shiny and I have used a relative and not absolute path, I was trying to only provide a minimal example but have confused things more in the process.

Here is the complete example:

```
output$apple_table <- renderReactable({
                                              reactable(apple_trending_apps1, 
                                                  style = list(fontFamily = "Arial, sans-serif", fontSize = "14px"),
                                                  resizable = TRUE, showPageSizeOptions = TRUE, 
                                                  onClick = "expand", highlight = TRUE, 
                                                  columns = 
                                                    list(
                                                      App = colDef(
                                                        minWidth = 200,
                                                        cell = function(value){
                                                                     image <- img(class = "appletrendingapplogo",
                                                                                   alt= "",
                                                                                   src = sprintf("images/%s.png", value))
                                                                   ) 
                                                                    tagList(
                                                                       div(style = list(display = "inline-block", width = "24px"), image),
                                                                       value
                                                                     )
                                                                   } )), 
                                                  theme = theme1)
              })

```

The images just don't render

Thank you,

**Comment by glin** [comment]
Ah, gotcha. For Shiny, you'll have to add external resource files to your app in one of two ways: https://shiny.rstudio.com/reference/shiny/1.4.0/resourcePaths.html

Either putting the images in a `www/` subdirectory in your app directory, like `www/images`:
```
.
+-- app.R
+-- www
    +-- images
        +-- beaver.png
        +-- cow.png
```

Or using `addResourcePath(prefix, directoryPath)` to have Shiny serve a directory of files under `/prefix`. Like `addResourcePath("images", "my-images")` to serve the `my-images/` folder under `/images`.

With either way, you should be able to use relative links like `images/beaver.png` from your app.

**Comment by davelorino** [comment]
Thank you, totally resolved! My bad, I didn't realise this was essential for shiny apps to access images from within the www folder.

Thanks again for your replies and especially for your amazing library!

**Comment by glin** [comment]
👍 

It's definitely not straightforward either way, so I've added these tips to the cookbook doc: https://glin.github.io/reactable/articles/cookbook/cookbook.html#embed-images

**Comment by EmilieDS** [comment]
Hey, I am facing the same issue as @davelorino , except I am not doing it with shiny. I used the base example and the table renders but the images doesn't. I get the broken image and alt text. The flag image is in the same folder as my code.
 `
library(htmltools)

data <- data.frame(
  Animal = c("beaver", "cow", "wolf", "goat"),
  Body = c(1.35, 465, 36.33, 27.66),
  Brain = c(8.1, 423, 119.5, 115)
)

reactable(data, columns = list(
  Animal = colDef(cell = function(value) {
    image <- img(src = "flag.png", alt = "alt")
    tagList(
      div(style = list(display = "inline-block", width = "45px"), image),
      value
    )
  }),
  Body = colDef(name = "Body (kg)"),
  Brain = colDef(name = "Brain (g)")
))

`

I hope someone can help me !
![Capture](https://user-images.githubusercontent.com/38395742/127512418-6f215da1-75bf-4c11-b062-fada93b23016.PNG)
