### ISSUE TITLE
Cell Index on click

### ISSUE THREAD

**Issue by ttrevisan18** [glin/reactable#47]
Phenomenal package! Really incredible work. One feature request, is it possible to modify getReactableState so that it can also return the row and column index of a selected cell, even when check boxes are not present? 

DT describes this in 2.1.3 https://rstudio.github.io/DT/shiny.html. 

I know the example below is provided, but this seems to be contained within the reactable and can not pass the row/column index onto another function.

reactable(iris[1:5, ], onClick = JS("
  function(rowInfo, colInfo) {
    window.alert('clicked row ' + rowInfo.index + ', column ' + colInfo.id)

    // Send the click event to Shiny (note that the row indices start at 0 in JavaScript)
    if (window.Shiny) {
      Shiny.onInputChange('clicked', { column: colInfo.id, index: rowInfo.index + 1 })
    }
  }
"))

**Comment by glin** [comment]
Hi,

If you want to get the row/column index of the clicked cell in Shiny, you can use that example and access the click info in Shiny like `input$clicked`. For example, an app that sends cell click info to the  `tbl_cell_clicked` input, and uses `input$tbl_cell_clicked` in a text output:
```r
library(shiny)
library(reactable)

ui <- fluidPage(
  reactableOutput("tbl"),
  verbatimTextOutput("tbl_cell_clicked")
)

server <- function(input, output) {
  output$tbl <- renderReactable({
    reactable(
      iris,
      bordered = TRUE,
      onClick = JS("function(rowInfo, colInfo) {
        Shiny.onInputChange('tbl_cell_clicked', { column: colInfo.id, row: rowInfo.index + 1 })
      }")
    )
  })

  output$tbl_cell_clicked <- renderPrint({
    if (is.null(input$tbl_cell_clicked)) {
      return(NULL)
    }
    column <- input$tbl_cell_clicked$column
    row <- input$tbl_cell_clicked$row
    value <- iris[row, column]
    writeLines("Clicked cell:\n")
    list(column = column, row = row, value = value)
  })
}

shinyApp(ui, server)
```

The click event could be added to `getReactableState()`, but I'm on the fence about whether it's too specific to build in. I'd also like to improve accessibility of the cell click actions first -- currently, there's no way to indicate whether a cell has been clicked/selected, and there's no way to click cells using a keyboard.

Let me know if this answers your question, or if you'd like to see support for proper cell selection built in. I'm happy to take that as a feature request if so.

**Comment by ttrevisan18** [comment]
this certainly solves for the solution I was looking for. If you don't want to build this into the getReactableState(), I certainly understand. This works perfectly.

Thanks again - really great package that I have enjoyed using!

**Comment by amanthapar** [comment]
Hello,
Hope someone sees this message. This is working on our Shiny standalone App. BUT it is not working on when we use it on Shiny Modules. ( https://shiny.rstudio.com/articles/modules.html ). Our UI Module does not detect the click. 

any idea why that might be? Or what changes we might have to make in order for it to work? could it be a namespace problem? The other features from Reactable seem to work ok, except this click event for row index. 

```
onClick = JS("function(rowInfo, colInfo) {
        Shiny.onInputChange('tbl_cell_clicked', { column: colInfo.id, row: rowInfo.index + 1 })
      }")
```

**Comment by ttrevisan18** [comment]
> Hello,
> Hope someone sees this message. This is working on our Shiny standalone App. BUT it is not working on when we use it on Shiny Modules. ( https://shiny.rstudio.com/articles/modules.html ). Our UI Module does not detect the click.
> 
> any idea why that might be? Or what changes we might have to make in order for it to work? could it be a namespace problem? The other features from Reactable seem to work ok, except this click event for row index.
> 
> ```
> onClick = JS("function(rowInfo, colInfo) {
>         Shiny.onInputChange('tbl_cell_clicked', { column: colInfo.id, row: rowInfo.index + 1 })
>       }")
> ```

I am not sure how familiar you are with using Shiny modules, but they work by modifying the name of all the objects within the module using the namespace function. For example:

ns = NS('test')
ns('Table')

makes the name of the object 'test-Table'. When you reference it in the JS, you will need to add the ID from the namespace to the front of your JS object. assuming your namespace id is "test", the example above would need to look like the JS below:

onClick = JS("function(rowInfo, colInfo) {
        Shiny.onInputChange('test-tbl_cell_clicked', { column: colInfo.id, row: rowInfo.index + 1 })
      }")

I have not tested this, but it should work. Good luck.
