### ISSUE TITLE
Allow flexible column width specification

### ISSUE THREAD

**Issue by richierocks** [glin/reactable#53]
Currently, you can control the width of the whole reactable using the `width` argument. Where a data frame contains very short of very long content, it would be helpful to either 

1. automatically guess sensible column widths (maybe just fit to the content based on max number of characters), or
2. allow users to specify individual column widths (in pixels, or as a percentage of the total)

Here's an example of a reactable with a column of narrow content (height) and wide content (films). Since each column has the same width, it is an inefficient use of space.

``` r
library(reactable)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
sw <- starwars %>% select(name, height, films)
reactable(sw)
```

![](https://i.imgur.com/VKCf2Bk.png)

If I try to specify the widths for each column, I get an error.

``` r
reactable(sw, width = c(150, 50, 400))
#> Error in htmltools::validateCssUnit(width): CSS units must be a single-element numeric or character vector
```

**Comment by richierocks** [comment]
So naturally filing an issue meant I immediately spotted the solution, in `?colDef`.

``` r
reactable(
  sw, 
  columns = list(
    name = colDef(width = 100),
    height = colDef(width = 50),
    films = colDef(width = 400)
  ),
  fullWidth = FALSE
)
```

![](https://i.imgur.com/Ak34CH1.png)

**Comment by glin** [comment]
Sorry about that. I've been wanting to add documentation for column widths forever, but it's kind of hard to explain 😅

Here's an initial take on that: https://glin.github.io/reactable/articles/examples.html#column-widths

In short, reactable (and the underlying table library) doesn't use an HTML table element, so there is no automatic resizing based on content width. You have to be precise with column widths, which can be kind of annoying.

Of the column width options, I would recommend using only `minWidth` or `width` in most cases. With `minWidth`, you can control both the percentage width and minimum width of the column -- see the link above for examples. `width` would be for columns with known content lengths.

For example, you could make the table above more responsive like this:
```r
library(reactable)
library(dplyr)

sw <- starwars %>% select(name, height, films)

reactable(
  sw,
  columns = list(
    name = colDef(width = 100),
    height = colDef(width = 100),
    films = colDef(minWidth = 200)
  ),
  style = list(maxWidth = 600)
)
```
This table will stretch to 600px if possible, but shrink down to 400px if not.

**Comment by richierocks** [comment]
Thanks. To save future users falling over this, it might be worth updating the `?reactable` documentation to mention where the solution is described. Some possibilities:

1. Change the doc for the [width](https://github.com/glin/reactable/blob/master/R/reactable.R#L93) param to say something like "Width of whole reactable. To set column widths individually, see `?colDef`."
2. Add a link to `?colDef` in the [see also](https://github.com/glin/reactable/blob/master/R/reactable.R#L108-L109) section of the doc.

**Comment by glin** [comment]
I've updated the docs with both of those changes. Thanks for the suggestions!

**Comment by sol-libesman** [comment]
Hi Glin, thank you for all the help! I have a column "additional comments" that is up to 500 words. It ruins the formatting of my table so I wanted to put the additional information as expandable row details for that individual column.  The problem is when I expand that column it's so wide that it goes off-screen making it hard to read. As a result, I was wondering if there is a way to limit the max width of the expandable row? Thank you!
