### ISSUE TITLE
Tweet embedding breaks when content change

### ISSUE THREAD

**Issue by tvroylandt** [glin/reactable#55]
Thanks for this nice package !

I have a problem when I try to embed tweet directly in the table as here : https://morphea.netlify.app/
Code is here : https://github.com/tillac/morphea/blob/master/Rmd/tw_table.Rmd

It works well because I included a `script` outside of the table. But when I change something (go to page 2 as an example or filter the table), the embedding breaks as if the JS needed to be reload ? 

The problem stays the same if I use a `class`, a cell function in JS or a `rowClass`. It works on the first try and break after it.

How could it be possible to keep the embedding when the content of the table (filtering / changing page) change ?

Thank you !

EDIT : see below for a new example. The old one has been change and doesn't reflect the problem anymore.

**Comment by tvroylandt** [comment]
The example above wasn't really reproducible so I set up a new one with the same problem :
- code here : https://github.com/tvroylandt/react_tweet/blob/master/react_tw.Rmd
- page with problem shown here : https://tvroylandt.github.io/react_tweet/react_tw

The problem is the same : we can see the Tweet right on a first view but when we change something (filtering or new page), it breaks everything. As if we needed a callback.

**Comment by glin** [comment]
Hi,

Thanks for the reproducible example. It looks like the widgets.js script only works on pages with static content. According to the docs, you additionally need to call `twttr.widgets.load()` when any content gets loaded dynamically (e.g., when changing pages in the table): https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/scripting-loading-and-initialization

I think ideally, the embedded Tweets would be an htmlwidget where `twttr.widgets.load()` gets called in the widget's `renderValue()` function. Then it'd work out of box in both reactable and Shiny when using dynamic UI.

Alternatively, reactable doesn't have a general callback function, but you could use something like the `rowClass` or `rowStyle` callbacks, which run on table state changes:
```r
df_tweets %>%
  mutate(
    embed_url = paste0(
      "https://publish.twitter.com/oembed?url=https://twitter.com/",
      tolower(screen_name),
      "/status/",
      status_id
    )
  ) %>%
  select(embed_url) %>%
  reactable(
    filterable = TRUE,
    defaultPageSize = 5,
    columns = list(embed_url = colDef(
      name = "Tweet",
      cell = function(value) {
        ret <- value %>%
          httr::GET() %>%
          httr::content()
        ret$html
      },
      html = TRUE
    )),
    rowClass = JS("function() {
      const el = document.getElementById('tweets-tbl')
      twttr.widgets.load(el)
    }"),
    elementId = "tweets-tbl"
  )
```

This will work, but it is a bit weird to use `rowClass` like this.

Another alternative would be to create a custom React component that calls `twttr.widgets.load()` on some HTML when it renders:

````r
<script src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="https://cdn.jsdelivr.net/npm/create-react-class@15.6.3/create-react-class.min.js"></script>

```{js}
// Custom React component that loads embedded Tweet HTML
(function () {
  const Tweet = createReactClass({
    componentDidMount: function() {
      twttr.widgets.load(this.el)
    },
    setRef: function(el) {
      this.el = el
    },
    render: function() {
      const html = { __html: this.props.html }
      return React.createElement('div', { ref: this.setRef, dangerouslySetInnerHTML: html })
    }
  })
  
  window.embeddedTweet = function(html) {
    return React.createElement(Tweet, { html: html, key: html })
  }
})()
```

```{r}
df_tweets %>%
  mutate(
    embed_url = paste0(
      "https://publish.twitter.com/oembed?url=https://twitter.com/",
      tolower(screen_name),
      "/status/",
      status_id
    ),
    embed_html = map(embed_url, ~ httr::content(httr::GET(.x))$html)
  ) %>%
  select(embed_html) %>%
  reactable(
    filterable = TRUE,
    defaultPageSize = 5,
    columns = list(
      embed_html = colDef(
        name = "Tweet",
        cell = JS("function(cellInfo) {
          return embeddedTweet(cellInfo.value)
        }")
      )
    )
  )
```
````

This would be a more "proper" solution for reactable, but is pretty ugly and requires another script to make it work. It might be worth building this into reactable to make it easier to render dynamic content.

For now, I would either use the rowClass/rowStyle callback, or try out the htmlwidget route.

**Comment by tvroylandt** [comment]
Thank you a lot. This are fantastic solutions.
I implemented them here as a use case : https://morphea.netlify.app/

And here is a new blog post on this subject, which is only possible due to `reactable` : https://www.tillac-data.com/2020-search-your-tweets-with-an-automatic-pipeline/
