### ISSUE TITLE
Make "Grouping And Aggregation" > "Custom aggregate function" in examples more clear

### ISSUE THREAD

**Issue by domsle** [glin/reactable#60]
Hey there,

I am trying to understand, how can I make a custom aggregation function, that would calculate something based on other columns. The provided explanation is not clear for me.

Lets say my data is consisting of following columns: `Name`, `Group`, `Price `, `Units` and `Avg.Price`. I would like to group data in table using `Group` column, and for `Price` and `Units` columns it is clear to use the following code:

```
columns = list(
   `Price` = colDef(aggregate = "sum"),
   `Units` = colDef(aggregate = "sum")
)
```

However, I would like the aggregated value for `Avg.Price` to be calculated as a `sum(Price) / sum(Units)`. How could this be achieved? I think it would be a good simple example to be included in the [documentation](https://glin.github.io/reactable/articles/examples.html#grouping-and-aggregation-1) :)

**Comment by PaulC91** [comment]
I just figured out how to do this. You need to pass a javascript rendering function to the `aggregated` argument of `colDef`. Passing `cellInfo` to the JS function allows you to access the aggregated values of other columns:

```
columns = list(
  `Price` = colDef(aggregate = "sum"),
  `Units` = colDef(aggregate = "sum"),
  `Avg.Price` = colDef(
    aggregated = JS("function(cellInfo) {
                      const avg = cellInfo.row['Price'] / cellInfo.row['Units']; 
                      return '$' + avg.toFixed(2);
                    }")
  )
)
```

**Comment by glin** [comment]
Hi,

You can get access values from other columns using the `rows` argument in a custom aggregate function. `rows` will be an array containing the data of each row in the group, like this:
```js
// `rows` for a group of 3 rows
[
  {
    "Model": "Dynasty",
    "Manufacturer": "Dodge",
    "Price": 46.8,
    "Units": 2
  },
  {
    "Model": "Colt",
    "Manufacturer": "Dodge",
    "Price": 27.6,
    "Units": 5
  },
  {
    "Model": "Caravan",
    "Manufacturer": "Dodge",
    "Price": 57,
    "Units": 5
  }
]
```
Within the `rows` array, you can get the `Price` value of the first row like this:
```js
function(values, rows) {
  rows[0].Price
  // 46.8

  rows[0]['Price']
  // 46.8
}
```

Here's an example that calculates the aggregated value of an `Avg.Price` column as `sum(Price) / sum(Units)`:
```r
library(reactable)
library(dplyr)

set.seed(10)

data <- sample_n(MASS::Cars93[23:40, ], 30, replace = TRUE) %>%
  mutate(Price = Price * 3, Units = sample(1:5, 30, replace = TRUE)) %>%
  mutate(Avg.Price = Price / Units) %>%
  select(Model, Manufacturer, Price, Units, Avg.Price)

reactable(
  data,
  columns = list(
    Price = colDef(aggregate = "sum", format = colFormat(currency = "USD")),
    Units = colDef(aggregate = "sum"),
    Avg.Price = colDef(
      # Calculate the aggregated Avg.Price as `sum(Price) / sum(Units)`
      aggregate = JS("function(values, rows) {
        var totalPrice = 0
        var totalUnits = 0
        rows.forEach(function(row) {
          totalPrice += row['Price']
          totalUnits += row['Units']
        })
        return totalPrice / totalUnits
      }"),
      format = colFormat(currency = "USD")
    )
  ),
  groupBy = "Manufacturer"
)
```

![screenshot of table output](https://user-images.githubusercontent.com/20401866/87862967-7015d380-c91b-11ea-94f6-290edd21d68e.png)

This is a great use case for custom aggregate functions that I haven't thought of. I'll add this to the examples and improve the docs. Thanks for the suggestion.

Also, you could use a custom `aggregated` cell renderer as @PaulC91 shows, but it won't be sortable. The cell renderers affect display only, not data, so I'd recommend using an `aggregate` function where possible. The cell render functions do have access to more information though, like the aggregated values from other columns. Aggregate functions are more limited in what they can do.

**Comment by PaulC91** [comment]
Thanks for clarifying @glin and many thanks for this brilliant package. 

Out of curiosity, would this be the best way to add the same aggregate function to a footer row?
```
footer = JS("function(colInfo) {
        var totalPrice = 0
        var totalUnits = 0
        colInfo.data.forEach(function(row) {
          totalPrice += row['Price']
          totalUnits += row['Units']
        })
        return totalPrice / totalUnits
      }"
```

**Comment by glin** [comment]
@PaulC91 yep, that would be the best way to do it. Or if you don't need it to update with filtering, you can use an R function instead.

---

I've added this example to the docs here: https://glin.github.io/reactable/articles/examples.html#custom-aggregate-function. Thanks again for the suggestions.

**Comment by domsle** [comment]
Thanks for your help @glin @PaulC91 :)
