### ISSUE TITLE
Changing the design/css of rows

### ISSUE THREAD

**Issue by Rhydderch** [glin/reactable#62]
Hi,

How could I change the look of rows to the point where it doesn't look like a table anymore, to make them more visually distinct.
For example, adding padding, margin, rounded borders, a drop shadow, etc, while maintaining the filtering and search capabilities.

Maybe not to this extreme, but could just to give an idea :
![image](https://user-images.githubusercontent.com/3197629/87875934-d9a5e880-c9d4-11ea-8525-4ebedbaf130e.png)

Any guidance on how to achieve this would be very helpful.
Reactable seems like such a great package and a whole world of its own; it's hard for me to know where to start.

Perhaps this CSS would be a good start ?

.rt-tbody .rt-tr .rt-td{
	border-width:1px !important;
	border-style:hidden !important;
}

.rt-tbody .rt-tr{
	border-bottom-right-radius:7px;
	border-bottom-left-radius:7px;
	border-top-right-radius:7px;
	border-top-left-radius:7px;
	padding-left:5px;
	padding-right:5px;
	padding-top:5px;
	padding-bottom:5px;
	box-shadow:0px 0px 3px 0px #333333;
	border-width:1px;
	border-color:#95a5a6;
	margin-left:5px;
	margin-right:5px;
	margin-top:10px;
	margin-bottom:10px;
}

.rt-thead .rt-tr{
	margin-top:10px;
	margin-bottom:10px;
}

**Comment by glin** [comment]
Hi,

You can use the `rowStyle` arg in [`reactableTheme()`](https://glin.github.io/reactable/reference/reactableTheme.html) to add custom CSS to all rows. Check out the theming docs: https://glin.github.io/reactable/articles/examples.html#theming

CSS like `.rt-tbody .rt-tr` is also an option, but the reactable CSS classes are undocumented and still subject to change. They're probably mostly safe to use, but I'd recommend either using a theme or adding your own classes to the table where possible (e.g., `rowClass`): https://glin.github.io/reactable/articles/examples.html#custom-css

There aren't any examples in the docs that modify the row style, but here's an old, discarded example that had a custom margin and rounded borders on rows:
```r
library(reactable)

reactable(
  MASS::Cars93[, c("Manufacturer", "Model", "Type", "Price", "MPG.city")],
  highlight = TRUE,
  details = function(index) paste("Details for row", index),
  filterable = TRUE,
  theme = reactableTheme(
    color = "hsl(228, 20%, 90%)",
    backgroundColor = "hsl(228, 40%, 21%)",
    borderColor = "transparent",
    highlightColor = "hsl(228, 40%, 17%)",
    style = list(padding = "2px 16px"),
    headerStyle = list(backgroundColor = "hsl(228, 40%, 21%)", color = "hsl(228, 20%, 80%)"),
    rowStyle = list(backgroundColor = "hsl(228, 45%, 14%)", margin = "2px 0", borderRadius = "4px"),
    inputStyle = list(
      backgroundColor = "hsl(228, 45%, 14%)",
      borderColor = "rgba(255, 255, 255, 0.12)",
      borderRadius = "4px",
      "&:hover, &:focus" = list(borderColor = "rgba(255, 255, 255, 0.2)")
    ),
    selectStyle = list(
      backgroundColor = "hsl(228, 45%, 14%)",
      borderColor = "rgba(255, 255, 255, 0.12)",
      borderRadius = "4px"
    ),
    pageButtonStyle = list(margin = "0 2px", borderRadius = "30px"),
    pageButtonHoverStyle = list(backgroundColor = "hsl(228, 45%, 14%)"),
    pageButtonActiveStyle = list(backgroundColor = "hsl(228, 45%, 12%)"),
    pageButtonCurrentStyle = list(boxShadow = "0 0 2px #fff")
  )
)
```

![screenshot of table output](https://user-images.githubusercontent.com/20401866/87890434-23ee9000-c9fc-11ea-8a58-9a8baaabadc3.png)

**Comment by Rhydderch** [comment]
Thanks a lot for your detailed answer. It really helped me get a better result.
By the way, congrats on the documentation, there's so much info! It really helps.

![image](https://user-images.githubusercontent.com/3197629/88082375-ff242500-cb81-11ea-9d6f-2151a29b0f7a.png)
