### ISSUE TITLE
Selection box positioning with grouping

### ISSUE THREAD

**Issue by ajirnyi** [glin/reactable#71]
When both grouping and selection is present, is it possible to control where the selection boxes are (for example, place them in the leftmost column)?

**Comment by glin** [comment]
This isn't possible today, but it's a great suggestion. I'll be reworking how selection and grouping work underneath in the next few months, and will look into making this happen.

**Comment by glin** [comment]
The selection column is now the first column in the table in the development version (https://github.com/glin/reactable/commit/d9ac371fb1a5a06f5e878bedf1bfcabbeac2838d). It should be placed before the `groupBy` columns and the row details columns. Here's a comparison of before vs. after:

```r
reactable(
  MASS::Cars93[, 1:4],
  selection = "multiple",
  groupBy = "Manufacturer",
  details = function(i) paste("Details for row", i),
  defaultPageSize = 5,
  bordered = TRUE
)
```


Before:
![old reactable version](https://user-images.githubusercontent.com/20401866/104133550-e3882300-5349-11eb-8522-8d5409f6e2cd.png)

After:
![new reactable version](https://user-images.githubusercontent.com/20401866/104133557-ec78f480-5349-11eb-951c-ba3a69efa9f2.png)

The row details column could be moved before the `groupBy` columns as well, so I might do that later.
