### ISSUE TITLE
Sticky columns with horizontal scrolling

### ISSUE THREAD

**Issue by ajirnyi** [glin/reactable#72]
Is it possible to have a sticky column in a table that has horizontal scrolling, a la kableExtra (except the main issue with their approach is that it's not IE compatible).

**Comment by glin** [comment]
Yes, see here for a couple examples: https://glin.github.io/reactable/articles/examples.html#sticky-columns

These examples are still based on `position: sticky`, however, so they won't work in IE 11. For an IE11-compatible solution, you might be able to achieve something through `position: absolute`, but I haven't looked into it.

**Comment by glin** [comment]
Sticky columns are now built into reactable in the dev version:

> * Sticky columns are now supported using a new `sticky` argument in `colDef()` and `colGroup()` ([#19](https://github.com/glin/reactable/issues/19), [#72](https://github.com/glin/reactable/issues/72), [#141](https://github.com/glin/reactable/issues/141)).

It's still not compatible with IE11, but IE11 compatibility is gradually becoming less of an issue with its upcoming end of support.
