### ISSUE TITLE
Multiple styles 

### ISSUE THREAD

**Issue by davidfgeorge** [glin/reactable#73]
How do I define multiple styles for a column? For example  render a column value as a link, and make that same specific column non-filterable. Otherwise _'reactable'_ is super to use.
Thank you.

**Comment by glin** [comment]
Hi, could you clarify what you mean by "multiple styles"? I was thinking of CSS styles for that, like a `font-weight: bold; font-size: 14px` style. You can define multiple styles for a column using the `class` and `style` arguments on a `colDef()`. There are examples scattered throughout the docs, but here's one for using CSS classes: https://glin.github.io/reactable/articles/examples.html#custom-css

Rendering links and making columns non-filterable aren't what I think of styling, but there are examples on how to do these here:

- Rendering links: https://glin.github.io/reactable/articles/cookbook/cookbook.html#insert-links
- Disabling filtering on a specific column: https://glin.github.io/reactable/articles/examples.html#filtering

**Comment by davidfgeorge** [comment]
Hi Greg, I hope that you, your family and all those close to you are safe and well.

Thank you for the advice and suggestions, and please pardon my use of possibly incorrect terminology as my knowledge of HTML/CSS/ JavaScript is very limited.

It is straight forward to associate data values with rating stars; value colouring; mini bar chart and url links for example, which I have achieved in my testing. I have learned a lot from the documentation and practical examples you provide, but as yet I cannot find a way to use ‘columns = list(  … value_name = colDef(…)’ on a data column to specify given value as being both a currency and colour coded for example.

I will re-read/follow-up the references you provided. In the meantime, what I have implemented thus far is working very well.
Cheers.

David F. George
Need little, want less, give more
davidfgeorge@hotmail.com<mailto:davidfgeorge@hotmail.com>
LinkedIn<http://uk.linkedin.com/in/dfgeorge>
Mobile: +44 7468 858638

**Comment by glin** [comment]
Thanks! And same to you.

If you can provide any code examples, even if still in progress, that might help. Otherwise, I guess you want to apply styling and data formatting to a column at the same time? The usual way to do that would be to use both the `style` and `format` arguments on `colDef()` at the same time.

For example, to format as currency and apply conditional coloring:
```r
# Adapted from https://glin.github.io/reactable/articles/examples.html#conditional-styling
reactable(
  sleep[1:6, ],
  columns = list(
    extra = colDef(
      format = colFormat(currency = "USD", separators = TRUE),
      style = function(value) {
        if (value > 0) {
          color <- "#008000"
        } else if (value < 0) {
          color <- "#e00000"
        } else {
          color <- "#777"
        }
        list(color = color, fontWeight = "bold")
      }
    )
  )
)
```

Or if you need custom formatting, you can combine `style` and a custom `cell` renderer:
```r
reactable(
  sleep[1:6, ],
  columns = list(
    extra = colDef(
      cell = function(value) {
        value <- paste0("$", format(value, nsmall = 2))
      },
      style = function(value) {
        if (value > 0) {
          color <- "#008000"
        } else if (value < 0) {
          color <- "#e00000"
        } else {
          color <- "#777"
        }
        list(color = color, fontWeight = "bold")
      }
    )
  )
)
```

**Comment by davidfgeorge** [comment]
Hi Greg. Many thanks for your helpful email. That worked for me, and so I should be able to make more use of the capabilities of reactable now.
Cheers,

David F. George
Need little, want less, give more
davidfgeorge@hotmail.com<mailto:davidfgeorge@hotmail.com>
LinkedIn<http://uk.linkedin.com/in/dfgeorge>
Mobile: +44 7468 858638
