### ISSUE TITLE
Change Sort Icon Character

### ISSUE THREAD

**Issue by ixodid198** [glin/reactable#75]
It is documented [here](https://glin.github.io/reactable/articles/examples.html#sorting-1) how to show the sortable arrows. 

Is it possible to change the arrows to different characters?
Three new ones for up, down, up-down.

**Comment by glin** [comment]
It's possible if you hide the default sort icons using `showSortIcons = FALSE`, and add your own sort icons. There's one example of using bars for the sort indicators here: https://glin.github.io/reactable/articles/cookbook/cookbook.html#custom-sort-indicators. And another example of using triangles here: https://glin.github.io/reactable/articles/custom-sort-icons.html.

Alternatively, you could also use a font with custom arrows, like in this example: https://glin.github.io/reactable/articles/cookbook/cookbook.html#custom-fonts

So it's not that easy today, but I could see a future version having sort icons customizable through theme options:
```r
reactableTheme(
  sortAscIcon = "↑",
  sortDescIcon = "↓",
  sortDefaultIcon = htmltools::tags$svg()  # some SVG icon or image
)
```

**Comment by ixodid198** [comment]
Great. Thank-you.
