### ISSUE TITLE
Cross browser styling with Reactable checkboxes

### ISSUE THREAD

**Issue by ixodid198** [glin/reactable#82]
The checkbox styling that is indicated here:

```
library("reactable")
library("tidyverse")
       
reactable(
  iris[1:4, ],
  selection = "multiple",
  defaultSelected = c(1, 3),
  borderless = TRUE,
  onClick = "select",
  theme = reactableTheme(
    rowSelectedStyle = list(backgroundColor = "#eee", boxShadow = "inset 2px 0 0 0 #ffa62d")
  )
)
```
Is only visible on Chrome. I don't see it on Safari, Edge , or Firefox. Is there a way to get the styling to appear on a wider selection of browsers?

Chrome, Edge and Firefox images:
![chrome_Screenshot 2020-09-30 115037](https://user-images.githubusercontent.com/12522241/94710422-d7390680-0314-11eb-81cc-e74f9f97759b.png)
![Edge_Screenshot 2020-09-30 115143](https://user-images.githubusercontent.com/12522241/94710423-d7390680-0314-11eb-8328-dfafb40f8c16.png)
![Firefox_Screenshot 2020-09-30 115250](https://user-images.githubusercontent.com/12522241/94710424-d7390680-0314-11eb-994b-3f9f226109ec.png)

**Comment by glin** [comment]
Hi, 

Those are the browser's native checkbox elements. reactable doesn't style them -- those are the browser's built-in styles for checkboxes. 

Getting checkboxes to look consistent across browsers is fairly tricky to do, from what I understand. This article has some of the history behind it: https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms.

It should at least be possible to apply some limited styling to checkboxes though. You could use a `reactableTheme()` or regular CSS to target `input[type='checkbox']` elements in the table. For example, I found this article from searching for "styling native checkboxes": https://dev.to/felipperegazio/styling-native-radio-and-checkbox-inputs-css-only-58ci

Adapting this for reactable, you could use a theme like:
```r
reactable(
  mtcars,
  selection = "multiple",
  theme = reactableTheme(
    style = list(
      "input[type='checkbox']" = list(
        appearance = "none",
        border = "1px solid #ccc",
        width = "14px",
        height = "14px",
        display = "flex",
        alignItems = "center",
        justifyContent = "center"
      ),
      "input[type='checkbox']:checked::before" = list(
        content = "''",
        width = "8px",
        height = "8px",
        background = "#ffa500",
        borderRadius = "1px"
      )
    )
  )
)
```

![reactable with custom styled checkboxes](https://user-images.githubusercontent.com/20401866/94998336-cf789c80-0576-11eb-8aab-5298c991085c.png)

The downside with this method, which relies on `appearance: none`, is that it doesn't work on IE11: https://caniuse.com/?search=appearance

Fancier custom checkboxes will completely hide the native checkbox and show their own custom elements. This isn't possible for now, but it may be in the future by having selection columns support custom rendering.

**Comment by ixodid198** [comment]
Understood. Thanks again.
