### ISSUE TITLE
Access data in cell function without naming

### ISSUE THREAD

**Issue by StephanFurger** [glin/reactable#84]
I want to create a general cell function which can be applied to several numeric columns at once. This would allow the cell function not to have to be specified by name for each variable.

So instead of naming `data$MPG.city` explicitly. 
```
  reactable(data, columns = list(
              MPG.city = colDef(
                name  = "MPG (city)", 
                align = "left", 
                cell  = function(value) {
                  width <- paste0(value / max(data$MPG.city) * 100, "%")
                  bar_chart(value, width = width)
                  })))
```

I would like to access data in a more general way. Is this already possible?
```
  reactable(data, columns = list(
              MPG.city = colDef(
                name  = "MPG (city)", 
                align = "left", 
                cell  = function(value, name) {
                  width <- paste0(value / max(data[name]) * 100, "%")
                  bar_chart(value, width = width)
                  })))
```

Thanks a lot in advance for your help!

**Comment by glin** [comment]
Hi, this is indeed possible today. Check out the custom cell rendering docs: https://glin.github.io/reactable/articles/custom-rendering.html#r-render-function

Cell render functions in R get the column name as the third argument, so you could do something like:
```r
  reactable(data, columns = list(
              MPG.city = colDef(
                name  = "MPG (city)", 
                align = "left", 
                cell  = function(value, index, name) {
                  width <- paste0(value / max(data[[name]]) * 100, "%")
                  bar_chart(value, width = width)
                  })))
```

I would also recommend indexing `data` with double brackets, i.e. `data[[name]]`, so you get a vector instead of a data frame.

**Comment by StephanFurger** [comment]
@glin Thanks a lot for the help!
