### ISSUE TITLE
Barcharts are not aligned if labels have different length

### ISSUE THREAD

**Issue by werkstattcodes** [glin/reactable#85]
First, many thanks for this wonderful package!

I encountered an issue when trying in include a bar plot as outlined [here](https://glin.github.io/reactable/articles/cookbook/cookbook.html#bar-charts-1)

It all works fine, but when labels have different lengths (e.g. 99 vs 100), the bars start at different positions/are not aligned. I tried to solve this by padding i.e. " 99" (`str_pad(label, width=3, side=c("left"), pad=" ")`) However, it seems like that spaces are removed when rendering the barchart ("_99" however works).  

Unfortunately, the image created below by the `reprex` doesn't really show the issue. But running the code below in R hopefully makes clear what I am referring to.

``` r
library(htmltools)
library(reactable)
library(tidyverse)


data <- MASS::Cars93 %>% 
  select(Make, MPG.city) %>% 
  mutate(MPG.city=MPG.city+80) %>% 
  filter(between(MPG.city, 99, 100))

# Render a bar chart with a label on the left
bar_chart <- function(label, width = "100%", height = "16px", fill = "#00bfc4", background = NULL) {
  bar <- div(style = list(background = fill, width = width, height = height))
  chart <- div(style = list(flexGrow = 1, marginLeft = "8px", background = background), bar)
  label <- str_pad(label, width=3, side=c("left"), pad=" ")
  div(style = list(display = "flex", alignItems = ""), label, chart)
}

reactable(data, columns = list(
  MPG.city = colDef(name = "MPG (city)", align = "left", cell = function(value) {
    width <- paste0(value / max(data$MPG.city) * 100, "%")
    bar_chart(value, width = width)
  })))
```

![](https://i.imgur.com/I6j8JJ3.png)

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by glin** [comment]
Hi, check out the Twitter Followers tutorial for a discussion of the alignment issue and how to work around it: https://glin.github.io/reactable/articles/building-twitter-followers.html#add-bar-charts

In short, you'll need to style the fixed-width string labels with [`white-space: pre`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) to preserve the spaces, and a font where all the numbers have the same width. For example, adding a cell style like `style = list(whiteSpace = "pre", fontFamily = "monospace")`:

```r
reactable(data, columns = list(
  MPG.city = colDef(
    name = "MPG (city)",
    align = "left",
    style = list(whiteSpace = "pre", fontFamily = "monospace"),
    cell = function(value) {
      width <- paste0(value / max(data$MPG.city) * 100, "%")
      bar_chart(value, width = width)
    }
  )
))
```

I'll add a tip about this in the bar charts example.

**Comment by werkstattcodes** [comment]
many thank!
