### ISSUE TITLE
Ability to access selected column or cell?

### ISSUE THREAD

**Issue by Avatoo** [glin/reactable#89]
Hi, thanks for the great package! I wonder if it's possible to access the index of a column or cell? This feature would be ideal in my project where we would like to display distribution graph of values of columns in Shiny app. 

From browsing documentation, I understand {reactable} doesn't have this feature, but could anyone point me to a workaround or some hack way?

Much appreciated.

**Comment by algo-se** [comment]
Hi, I don´t know about accessing index of columns/cells, but in order to "display distribution graph of values of columns" maybe [this example](https://glin.github.io/reactable/articles/examples.html#embedding-html-widgets-footers) is useful to you? It uses the `footer` argument to embed a sparklike type of chart.

**Comment by mingsnu** [comment]
Similar question here, do you have the plan to add Row/Column/Cell Selection feature as DT package: https://rstudio.github.io/DT/shiny.html
Thanks a lot for creating this powerful package! Really like it!

**Comment by Avatoo** [comment]
Thanks for the hint @algo-se. Yea that's a workaround, but my ideal solution is that user can click on any column and view a plot on a popup window.

I've adapted from a [SO](https://stackoverflow.com/questions/39295123/pop-up-window-after-clicking-on-dt-in-shiny) exmaple where actionButtons lead to this full sized plot via {DT}. 
![image](https://user-images.githubusercontent.com/6826099/96947543-692ecc00-14db-11eb-8f42-2388ed32c255.png)

There is quite a bit of JS code involved, and I'm struggling to achieve similar results with {reactable}. Is that possible?

Please find my attempts with the two packages [here](https://gist.github.com/Avatoo/49a0fc841f0249e360d42c7e2ca64c50#file-attempts-r).

**Comment by algo-se** [comment]
I don´t have time now, but I think the structure should be something like this:
```
  df <- rbind(Plot = shinyInput(actionButton, ncol(mymtcars), "btn", label = "", icon = icon('chart-line')),
                      mymtcars)
  df <- df[,c(1:3)]
  
  output$mytable <- renderReactable({
    reactable(df, columns = list(
      mpg = colDef(
        cell = JS("function(cellInfo) { 
        if( cellInfo.viewIndex === 0 ) { 
            return { Shiny.bindAll(this.api().table().node()); } 
                } else { cellInfo.value } 
        }")
      ),
      cyl = colDef(
        cell = JS("function(cellInfo) { 
        if( cellInfo.viewIndex === 0 ) { 
            return { Shiny.bindAll(this.api().table().node()); } 
                } else { cellInfo.value } 
        }")
      ),
      disp = colDef(
        cell = JS("function(cellInfo) { 
        if( cellInfo.viewIndex === 0 ) { 
            return { Shiny.bindAll(this.api().table().node()); } 
                } else { cellInfo.value } 
        }")
      )
      )),
      resizable = TRUE,
      showPageSizeOptions = TRUE,
      highlight = TRUE
    )
  })
```
Of course it would be easier to just put a selectInput (to select a column) and an actionButton (to draw the plot in a modalDialog) outside the table :P

**Comment by Avatoo** [comment]
The solution at the end of your last comment won! Single set of actionButton + column selector + plot looks pretty clean and did nicely. 

Thanks so much for the help @algo-se. I'm closing the issue for now. It would still be good to have the column wise index or a straightforward way to implement the above example in R :)

**Comment by glin** [comment]
Hi, reactable indeed does not support cell selection. It does support cell click actions though, which you could use to trigger a Shiny event when a cell is clicked: https://glin.github.io/reactable/articles/examples.html#custom-action

You could combine a custom cell click action with custom rendered buttons in the table to achieve something similar. For example:

```r
library(shiny)

# Add a row of NAs to the beginning for the plot buttons
data <- rbind(Plot = NA, mtcars)

ui <- fluidPage(
  reactable(
    data,
    defaultColDef = colDef(cell = function(value, index, name) {
      # Render a "show plot" button in the first row - this button won't
      # do anything by itself, but it will trigger the custom cell click action
      # when clicked.
      if (index == 1 && name %in% names(mtcars)) {
        htmltools::tags$button(shiny::icon("line-chart"), `aria-label` = "Show plot")
      } else {
        value
      }
    }),
    # Custom cell click action on the "show plot" row to send an event to Shiny.
    # input$plot_column will be used to access the clicked column name/ID.
    onClick = JS("
      function(rowInfo, colInfo) {
        if (rowInfo.index === 0) {
          if (window.Shiny) {
            Shiny.setInputValue('plot_column', colInfo.id, { priority: 'event' })
          }
        }
      }
    ")
  )
)

server <- function(input, output) {
  observeEvent(input$plot_column, {
    # Ignore the row names columns
    req(input$plot_column %in% names(mtcars))

    showModal(modalDialog(
      title = paste("Plot for", input$plot_column),
      plotOutput("plot")
    ))
  })

  output$plot <- renderPlot({
    req(input$plot_column %in% names(mtcars))

    plot(mtcars[[input$plot_column]])
  })
}

shinyApp(ui, server)
```

![app with modal shown](https://user-images.githubusercontent.com/20401866/97789226-af93c300-1b8c-11eb-9347-72591cb7815e.png)

In the future, reactable may support rendering Shiny inputs/outputs in cells (they're currently only supported in row details), and `shiny::actionButton`'s would make this much simpler.


I also like @algo-se's suggestion of putting the selection UI outside the table. A downside of having the plot buttons in cells is that they can be sorted, filtered, paged, etc., so it's kind of weird to see them disappear. I think plot buttons would fit better in either the header or footer, but it's not as easy to add custom click actions there right now.

**Comment by mingsnu** [comment]
Thanks a lot @glin and @algo-se!

**Comment by Avatoo** [comment]
thanks very much @glin, it looks elegant!
