### ISSUE TITLE
filterable - New feature request

### ISSUE THREAD

**Issue by kvnnp** [glin/reactable#90]
First of all, thank you for this amazing package. I spent an hour reading all the features and hard work you guys put into this gem.

Is it possible to expand filterable=TRUE's capability? For example, I'm working with data where I have values (in DAYS) from 1-200 for each subject. If I want to view subjects' data on DAY 2, the table will filter for all DAYS that begin with '2' (i.e. 2, 20, 21, ... 29, 200); however, I specifically want to view DAY 2 and only DAY 2. I added a space after typing in '2', but the table returns "No rows found". If this is already possible, how would I achieve this level of granularity?

**Comment by glin** [comment]
Hi, not right now, but custom filtering is tentatively planned for the next release. See https://github.com/glin/reactable/issues/9 for a related issue. You'll be able to choose between some built-in filtering methods (e.g., substring match, exact match), or a custom filtering method.

**Comment by glin** [comment]
Custom filtering is now possible in the latest development version (v0.2.3.9000):

> * Column filtering and table searching can now be customized. Learn more in the [Custom Filtering guide](https://glin.github.io/reactable/articles/custom-filtering.html).
>   * `reactable()` gains a `searchMethod` argument to use a custom JavaScript function for global table searching ([#222](https://github.com/glin/reactable/issues/222)).
>   * `colDef()` gains a `filterMethod` argument to use a custom JavaScript function for column filtering ([#9](https://github.com/glin/reactable/issues/9), [#90](https://github.com/glin/reactable/issues/90), [#145](https://github.com/glin/reactable/issues/145)).
>   * `colDef()` gains a `filterInput` argument to render a custom filter input for column filtering ([#9](https://github.com/glin/reactable/issues/9)).

There aren't any built-in filter methods yet, but you can write a custom filter method that does an exact match without too much effort. I can create an example if you need one, but otherwise, check out the [Custom Filtering guide](https://glin.github.io/reactable/articles/custom-filtering.html) for usage and a bunch of examples.

**Comment by asweej** [comment]
Could you please give an example to write a custom filter method that does an exact match

**Comment by asweej** [comment]
> Could you please give an example to write a custom filter method that does an exact match
JS("function(rows, columnId, filterValue) {
                                              return rows.filter(function(row) {
                                                return row.values[columnId] == filterValue
                                              })
                                            }")
