### ISSUE TITLE
Is it possible to remove parenthesis from groups?

### ISSUE THREAD

**Issue by algo-se** [glin/reactable#94]
Using `groupBy ` adds a default count to the group:

```
reactable(iris, 
  groupBy = "Species", 
  columns = list(
    Sepal.Length = colDef(aggregate = "count"),
    Sepal.Width = colDef(aggregate = "mean"),
    Petal.Length = colDef(aggregate = "sum"),
    Petal.Width = colDef(aggregate = "max")
    )
)
```
![image](https://user-images.githubusercontent.com/72490678/98793801-aaded280-2408-11eb-8193-13c195f8b3e6.png)
Is it possible to hide the default count? I´ve tried using custom JS with no success:

```
reactable(iris, 
          groupBy = "Species", 
          columns = list(
            Species = colDef(
              aggregated = JS("function(cellInfo) {
                return cellInfo.slice(0,-4);
              }"),
            ),
            Sepal.Length = colDef(aggregate = "count"),
            Sepal.Width = colDef(aggregate = "mean"),
            Petal.Length = colDef(aggregate = "sum"),
            Petal.Width = colDef(aggregate = "max")
          )
)
```
```
reactable(iris, 
          groupBy = "Species", 
          defaultColDef = colDef(
            aggregated = JS("function(cellInfo) {
              return cellInfo.slice(0,-4)
            }")
          ),
          columns = list(
            Sepal.Length = colDef(aggregate = "count"),
            Sepal.Width = colDef(aggregate = "mean"),
            Petal.Length = colDef(aggregate = "sum"),
            Petal.Width = colDef(aggregate = "max")
          )
)
```
Best regards.

**Comment by glin** [comment]
It's not possible today, even with custom JS, but it's been requested before (https://github.com/glin/reactable/issues/33). I'll put it on the list to include for the next release. The usage will probably look something like this:
```r
reactable(
  iris,
  groupBy = "Species",
  columns = list(
    Species = colDef(
      # Custom renderer for a grouped cell
      grouped = JS("function(cellInfo) {
        // Display just the cell value
        return cellInfo.value
        
        // Or display the cell value with the sub row count (the default)
        return cellInfo.value + '(' + cellInfo.subRows.length + ')'
      }")
    )
  )
)
```

**Comment by algo-se** [comment]
Thanks for the info Greg! I looked for the issue but did not find it.

Have a nice day :)

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by glin** [comment]
It's now possible to customize grouped cell rendering in the development version, using the syntax from above (https://github.com/glin/reactable/commit/1297d0cd28c1828bea8a9276d203715ac063b6f9).

> * `colDef()` gains a `grouped` argument to customize rendering for grouped cells in `groupBy` columns ([#33](https://github.com/glin/reactable/issues/33), [#94](https://github.com/glin/reactable/issues/94), [#148](https://github.com/glin/reactable/issues/148)).

I added some live examples of this to the docs: https://glin.github.io/reactable/articles/examples.html#grouped-cell-rendering

**Comment by mdubel** [comment]
With the current version 0.2.3 it can be achieved with custom css, see here: https://stackoverflow.com/a/70755757/9239948
