### ISSUE TITLE
Stroke outline of sorted Reactable column?

### ISSUE THREAD

**Issue by ixodid198** [glin/reactable#99]
I see how to change the background colour of a sorted column in a Reactable table:

```
library("reactable")

reactable(
  iris[1:5, ],
  defaultSorted = "Sepal.Width",
  defaultColDef = colDef(
    style = JS("function(rowInfo, colInfo, state) {
      // Highlight sorted columns
      for (var i = 0; i < state.sorted.length; i++) {
        if (state.sorted[i].id === colInfo.id) {
          return { background: 'rgba(0, 0, 0, 0.03)' }
        }
      }
    }")
  )
)
```
How is it possible to leave the background color as is and just draw an outline around the whole column? Something like this:

![stroke sort column](https://user-images.githubusercontent.com/12522241/100009268-a4ebd880-2d9c-11eb-924c-030df1b99739.png)

**Comment by glin** [comment]
This is a tough one. Cells are arranged in rows, not columns, so you can't just add a border to an entire column. The only thing I can think of is to add the left and right border to each cell, and then conditionally add a top or bottom border if the cell is first or last on the page.

Here's what I mean - you can change `2px` to some other width, or `#000` to some other color. I also use box-shadow for the top and bottom borders to prevent the cells from shifting vertically.

```r
library(reactable)

reactable(
  iris,
  defaultSorted = "Sepal.Width",
  defaultPageSize = 5,
  defaultColDef = colDef(
    style = JS("function(rowInfo, colInfo, state) {
      // Highlight sorted columns
      for (var i = 0; i < state.sorted.length; i++) {
        if (state.sorted[i].id === colInfo.id) {
          var style = {
            borderLeft: '2px solid #000',
            borderRight: '2px solid #000'
          }
          if (rowInfo.viewIndex === 0) {
            // Add top border
            style.boxShadow = 'inset 0px 2px 0px 0px #000'
          } else if (rowInfo.viewIndex === state.pageSize - 1) {
            // Add bottom border
            style.boxShadow = 'inset 0 -2px 0 0 #000'
          }
          return style
        }
      }
    }")
  )
)
```

![reactable output](https://user-images.githubusercontent.com/20401866/101266669-b5923c00-3716-11eb-9ed7-c0cbb9514725.png)

**Comment by ixodid198** [comment]
Very helpful. However, when I try to add multiple styles things don't work for me. Here's an example where I also wish to change the font size. Without using JS I would do this using a named list. Is that still the case with JS? What is going wrong here?

```library(reactable)

reactable(
  iris,
  defaultSorted = "Sepal.Width",
  defaultPageSize = 5,
  defaultColDef = colDef(
    style = list(
    style = JS("function(rowInfo, colInfo, state) {
      // Highlight sorted columns
      for (var i = 0; i < state.sorted.length; i++) {
        if (state.sorted[i].id === colInfo.id) {
          var style = {
            borderLeft: '2px solid #FCB700',
            borderRight: '2px solid #FCB700'
          }
            if (rowInfo.viewIndex === 0) {
            // Add top border
              style.boxShadow = 'inset 0px 2px 0px 0px #000'
            } else if (rowInfo.viewIndex === state.pageSize - 1) {
            // Add bottom border
              style.boxShadow = 'inset 0 -2px 0 0 #000'
            }
          return style
        }
      }
    }"),
    fontSize = "20px")
   
  )
)
```

**Comment by glin** [comment]
The `style` and `class` arguments only be a named list or a JS function, but not both at the same time. With a JS function, you can include any other default styles you want, so I'd recommend sticking with that. The only catch is that you have to write more JavaScript. For example, you could start with a default style object, then conditionally add styles to that:

```r
reactable(
  iris,
  defaultSorted = "Sepal.Width",
  defaultPageSize = 5,
  defaultColDef = colDef(
    style = JS("function(rowInfo, colInfo, state) {
      // Default styles
      var style = {
        fontSize: '20px'
      }

      // Highlight sorted columns
      for (var i = 0; i < state.sorted.length; i++) {
        if (state.sorted[i].id === colInfo.id) {
          style.borderLeft = '2px solid #000',
          style.borderRight = '2px solid #000'
          if (rowInfo.viewIndex === 0) {
            // Add top border
            style.boxShadow = 'inset 0px 2px 0px 0px #000'
          } else if (rowInfo.viewIndex === state.pageSize - 1) {
            // Add bottom border
            style.boxShadow = 'inset 0 -2px 0 0 #000'
          }
        }
      }

      return style
    }")
  )
)
```

An alternative to this, and what I do in many of the demos, is to use `style` for conditionally styling, and CSS classes for common/shared styling:

````r
```{r}
reactable(
  iris,
  defaultSorted = "Sepal.Width",
  defaultPageSize = 5,
  defaultColDef = colDef(
    # Add conditional styling through inline styles
    style = JS("function(rowInfo, colInfo, state) {
      // Highlight sorted columns
      for (var i = 0; i < state.sorted.length; i++) {
        if (state.sorted[i].id === colInfo.id) {
          var style = {
            borderLeft: '2px solid #000',
            borderRight: '2px solid #000'
          }
          if (rowInfo.viewIndex === 0) {
            // Add top border
            style.boxShadow = 'inset 0px 2px 0px 0px #000'
          } else if (rowInfo.viewIndex === state.pageSize - 1) {
            // Add bottom border
            style.boxShadow = 'inset 0 -2px 0 0 #000'
          }
          return style
        }
      }
    }"),
    # Add common cell styling through CSS
    class = "my-column"
  )
)
```

```{css}
/* Default cell styles for all columns */
.my-column {
  font-size: 20px;
}
```
````

**Comment by ixodid198** [comment]
Hello. Based on your answer that style arguments can only be a named list OR a JS function does that mean that if I want to combine your shade-cell-based-on-value technique (Demo Cookbook > Conditional formatting > Color scales) with the new outline edges of sorted cells then I need to convert the R code for shading the background of the cell based on value into JS?

Here, Petal.Length doesn't get the edge highlighting. My guess is because the cell shading either overwrites it or is a higher priority.

```
library(shiny)
library(reactable)

data <- iris[10:29, ]
orange_pal <- function(x) rgb(colorRamp(c("#ffe4cc", "#ff9500"))(x), maxColorValue = 255)

ui <- fluidPage(
  includeCSS("outline_column.css"),
  reactableOutput("table")
)

server <- function(input, output, session) {
  output$table <- renderReactable({
    
    reactable(data, 
              columns = list(
                Petal.Length = colDef(style = function(value) {
                normalized <- (value - min(data$Petal.Length)) / (max(data$Petal.Length) - min(data$Petal.Length))
                color <- orange_pal(normalized)
                list(background = color)
      })
    ),
    defaultColDef = colDef(
      # Add conditional styling through inline styles
      style = JS("function(rowInfo, colInfo, state) {
      // Highlight sorted columns
      for (var i = 0; i < state.sorted.length; i++) {
        if (state.sorted[i].id === colInfo.id) {
          var style = {
            borderLeft: '2px solid #000',
            borderRight: '2px solid #000'
          }
          return style
        }
      }
    }"),
      # Add common cell styling through CSS
      class = "my-column"
    )
    )
  })  
}

shinyApp(ui, server)
```

outline_column.css
```
/* Default cell styles for all columns */
.my-column {
  font-size: 20px;
}
```

I appreciate your generosity in answering my questions. However, if you feel that this is not the appropriate forum for this I'll understand.

**Comment by glin** [comment]
That's correct, the `style` argument from the column definition overrides the one from the default column definition. You would have to implement the conditional coloring in JavaScript, which could be tough without built-in color utilities like R's `colorRamp()`. There are probably JS libraries for creating color scales out there, but I have no experience with them.

The easier alternative I'd recommend is to move all the JavaScript based styling to CSS classes, so it doesn't conflict with the `style` arg. You can create 4 different CSS classes to add outlines, such as `outline-left` and `outline-right` to add left and right outlines, and conditionally add these classes in a `class` JS function:

````r
```{r}
library(reactable)

reactable(
  iris,
  defaultSorted = "Sepal.Width",
  defaultPageSize = 5,
  defaultColDef = colDef(
    class = JS("function(rowInfo, colInfo, state) {
      // Default classes
      var classes = 'my-column'

      // Highlight sorted columns
      for (var i = 0; i < state.sorted.length; i++) {
        if (state.sorted[i].id === colInfo.id) {
          classes += ' outline-left outline-right'
          if (rowInfo.viewIndex === 0) {
            // Add top border
            classes += ' outline-top'
          } else if (rowInfo.viewIndex === state.pageSize - 1) {
            // Add bottom border
            classes += ' outline-bottom'
          }
        }
      }

      return classes
    }")
  ),
  columns = list(
    Species = colDef(style = list(fontWeight = "bold"))
  )
)
```
````
The CSS classes for the first sorted cell would be `my-column outline-left outline-right outline-top` for example, and you could style those classes like:
````css
```{css}
/* Default cell styles for all columns */
.my-column {
  font-size: 20px;
}

.outline-left {
  border-left: 2px solid #000;
}

.outline-right {
  border-right: 2px solid #000;
}

.outline-top {
  box-shadow: inset 0 2px 0 0 #000;
}

.outline-bottom {
  box-shadow: inset 0 -2px 0 0 #000;
}
```
````

> I appreciate your generosity in answering my questions. However, if you feel that this is not the appropriate forum for this I'll understand.

I actually think questions like this are valuable for improving the package documentation and UX. GitHub Issues might not be the perfect forum, but at least they're easy for me to access. Maybe for the future, the new GitHub Discussions thing would be a better place for questions: https://github.com/glin/reactable/discussions. I don't know how useful it is yet, but we could try it out.

**Comment by ixodid198** [comment]
Super helpful as always. Thanks. I'll try the discussion area next time.
